# https://gptme.org/docs/config.html
[prompt]
about_user = "I am a curious human programmer."
response_preference = "Don't explain basic concepts"

[env]
MODEL = "openai/gpt-5-mini"
GPTME_CHECK = "false"
GPTME_COSTS = "true"
#GPTME_SUGGEST_LLM = "true"

[mcp]
enabled = true
auto_start = true

[[mcp.servers]]
name = "duckduckgo"
enabled = false
command = "uvx"
args = ["duckduckgo-mcp-server"]

[[mcp.servers]]
name = "browser-use"
enabled = true
command = "npx"
args = ["-y", "envmcp", "uvx", "browser-use[cli]", "--mcp"]
env = { BROWSER_USE_HEADLESS = "false", BROWSER_USE_DISABLE_SECURITY = "false" }

[[mcp.servers]]
name = "tavily"
enabled = true
command = "npx"
args = ["-y", "envmcp", "npx", "-y", "tavily-mcp"]

# One of these need to be set
# If none of them are, they will be prompted for on first start
#OPENAI_API_KEY = ""
#ANTHROPIC_API_KEY = ""
#OPENROUTER_API_KEY = ""
#XAI_API_KEY = ""
#GEMINI_API_KEY = ""
#GROQ_API_KEY = ""
#DEEPSEEK_API_KEY = ""

# Uncomment to use with Ollama
#MODEL = "local/<model-name>"
#OPENAI_BASE_URL = "http://localhost:11434/v1"

# Uncomment to change tool configuration
#TOOL_FORMAT = "markdown" # Select the tool formal. One of `markdown`, `xml`, `tool`
#TOOL_ALLOWLIST = "save,append,patch,ipython,shell,browser"  # Comma separated list of allowed tools
#TOOL_MODULES = "gptme.tools,custom.tools" # List of python comma separated python module path
