# Usage:
#   checkov -d .

enable-secret-scan-all-files: true
framework:
  - all
skip-path:
  - .git
  - .backup
  - etc/prompts/assistant/write_nuclei_template_rule.md
  - vscode/globalStorage
  - vscode/History
  - vscode/sync
  - vscode/workspaceStorage
