# Usage:
#   checkov -d .

enable-secret-scan-all-files: true
framework:
  - all
skip-path:
  - .backup
  - etc/prompts/assistant/write_nuclei_template_rule.md
  - etc/prompts/fabric/patterns/write_nuclei_template_rule/system.md
  - etc/prompts/fabric/.github
  - etc/prompts/fabric/Dockerfile
  - etc/prompts/fabric/web/jsconfig.json
  - etc/prompts/fabric/web/tsconfig.json
  - vscode/globalStorage
  - vscode/History
  - vscode/sync
  - vscode/workspaceStorage
