# Usage:
#   checkov -d .

enable-secret-scan-all-files: true
framework:
  - dockerfile
  - secrets
skip-path:
  - .backup
  - etc/goose
  - etc/prompts/fabric
  - etc/prompts/write_nuclei_template_rule.md
  - vscode/globalStorage
  - vscode/History
  - vscode/sync
  - vscode/workspaceStorage
