[default.extend-words]
fpr = "fpr"
sme = "sme"
gir = "gir"
gir1 = "gir1"

[files]
extend-exclude = [
  "CHANGELOG.md",
  "bin/lesspipe.sh",
  "bin/rsync_tmbackup.sh",
  "bin/trans",
  "bin/xpanes",
  "dotfiles/.aliases",
  "dotfiles/.gitconfig",
  "etc/ptpython/config.py",
  "etc/nvim/lazy-lock.json",
  "linux/brave/Default/Preferences",
  "macos/write_macos_defaults"
]
