#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

trap "printf '\nCaught ^C from user - exiting now\n' ; exit 130" INT

this_path=$(cd "$(dirname "$0")" && pwd)
bin_path="$this_path/bin"
backup_path="$this_path/.backup"
config_path="$HOME/.config/configent"

"$bin_path/setup_fonts"

if command -v code >/dev/null; then
  APP_NAME="Code" BIN_NAME="code" "$bin_path/setup_code"

  # VS Code has settings configured to read Cursor mcp.json
  if [ ! -r "$backup_path/.cursor/mcp.json" ]; then
    if [ -r "$HOME/.cursor/mcp.json" ]; then
      mkdir -p "$backup_path/.cursor"
      cp -P "$HOME/.cursor/mcp.json" "$backup_path/.cursor/mcp.json"
    fi
  fi
  mkdir -p "$HOME/.cursor"
  ln -sfnv "$config_path/mcp/mcp.json" "$HOME/.cursor/mcp.json"

  #APP_NAME="Code" BIN_NAME="code" "$bin_path/setup_kilocode"
fi

if command -v cursor >/dev/null; then
  APP_NAME="Cursor" BIN_NAME="cursor" "$bin_path/setup_code"

  # Create Cursor mcp.json
  if [ ! -r "$backup_path/.cursor/mcp.json" ]; then
    if [ -r "$HOME/.cursor/mcp.json" ]; then
      mkdir -p "$backup_path/.cursor"
      cp -P "$HOME/.cursor/mcp.json" "$backup_path/.cursor/mcp.json"
    fi
  fi
  mkdir -p "$HOME/.cursor"
  ln -sfnv "$config_path/mcp/mcp.json" "$HOME/.cursor/mcp.json"

  #APP_NAME="Cursor" BIN_NAME="cursor" "$bin_path/setup_kilocode"
fi

if command -v windsurf >/dev/null; then
  APP_NAME="Windsurf" BIN_NAME="windsurf" "$bin_path/setup_code"

  # Create Windsurf mcp_config.json
  if [ ! -r "$backup_path/.codeium/windsurf/mcp_config.json" ]; then
    if [ -r "$HOME/.codeium/windsurf/mcp_config.json" ]; then
      mkdir -p "$backup_path/.codeium/windsurf"
      cp -P "$HOME/.codeium/windsurf/mcp_config.json" \
        "$backup_path/.codeium/windsurf/mcp_config.json"
    fi
  fi
  mkdir -p "$HOME/.codeium/windsurf"
  ln -sfnv "$config_path/mcp/mcp.json" "$HOME/.codeium/windsurf/mcp_config.json"

  #APP_NAME="Windsurf" BIN_NAME="windsurf" "$bin_path/setup_kilocode"
fi

if command -v agy >/dev/null; then
  APP_NAME="Antigravity" BIN_NAME="agy" "$bin_path/setup_code"

  # Create Antigravity mcp.json
  if [ ! -r "$backup_path/.antigravity/mcp.json" ]; then
    if [ -r "$HOME/.antigravity/mcp.json" ]; then
      mkdir -p "$backup_path/.antigravity"
      cp -P "$HOME/.antigravity/mcp.json" "$backup_path/.antigravity/mcp.json"
    fi
  fi
  mkdir -p "$HOME/.antigravity"
  ln -sfnv "$config_path/mcp/mcp.json" "$HOME/.antigravity/mcp.json"

  #APP_NAME="Antigravity" BIN_NAME="agy" "$bin_path/setup_kilocode"
fi
