#!/bin/bash

trap "echo -e '\nCaught ^C from user - exiting now' ; exit 130" SIGINT

this_path=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

### Configuration ##############################################################

vscode_settings_path="$this_path/vscode"

### Symlink Visual Studio Code configuration ###################################

if [[ "$OSTYPE" = darwin* ]]; then
  user_path="$HOME/Library/Application Support/Code/User"
else
  user_path="$HOME/.config/Code/User"
fi

rm -rfv "${user_path}-old"
mv -v "$user_path" "${user_path}-old"
ln -snvi "$vscode_settings_path" "$user_path"

### Install VSCode extensions ##################################################

if which code &>/dev/null ; then
  # code --list-extensions | xargs -L 1 echo "code --force --install-extension"
  code --force --install-extension Arjun.swagger-viewer
  code --force --install-extension bencoleman.armview
  code --force --install-extension CoenraadS.bracket-pair-colorizer
  code --force --install-extension dbaeumer.vscode-eslint
  code --force --install-extension dnicolson.binary-plist
  code --force --install-extension eamodio.gitlens
  code --force --install-extension EditorConfig.EditorConfig
  code --force --install-extension eg2.vscode-npm-script
  code --force --install-extension esbenp.prettier-vscode
  code --force --install-extension golang.go
  code --force --install-extension Gruntfuggly.activitusbar
  code --force --install-extension hashicorp.terraform
  code --force --install-extension humao.rest-client
  code --force --install-extension mermade.openapi-lint
  code --force --install-extension ms-azure-devops.azure-pipelines
  code --force --install-extension ms-azuretools.vscode-bicep
  code --force --install-extension ms-azuretools.vscode-docker
  code --force --install-extension MS-CST-E.vscode-devskim
  code --force --install-extension ms-dotnettools.vscode-dotnet-runtime
  code --force --install-extension ms-python.python
  code --force --install-extension ms-python.vscode-pylance
  code --force --install-extension ms-toolsai.jupyter
  code --force --install-extension ms-toolsai.jupyter-keymap
  code --force --install-extension ms-vscode.azure-account
  code --force --install-extension ms-vscode.powershell
  code --force --install-extension ms-vsliveshare.vsliveshare
  code --force --install-extension msazurermtools.azurerm-vscode-tools
  code --force --install-extension naumovs.color-highlight
  code --force --install-extension Perkovec.emoji
  code --force --install-extension redhat.vscode-yaml
  code --force --install-extension stkb.rewrap
  code --force --install-extension tamasfe.even-better-toml
  code --force --install-extension teabyii.ayu
  code --force --install-extension timonwong.shellcheck
  code --force --install-extension tokoph.ghosttext
  code --force --install-extension VisualStudioExptTeam.vscodeintellicode
fi
