#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

trap "printf '\nCaught ^C from user - exiting now\n' ; exit 130" INT

this_path=$(cd "$(dirname "$0")" && pwd)

### Symlink Visual Studio Code configuration ###################################

if [ "$(uname -s)" = "Darwin" ]; then
  user_path="$HOME/Library/Application Support/Code/User"
else
  user_path="$HOME/.config/Code/User"
fi

if [ ! -d "${user_path}-old" ]; then
  cp -R "$user_path" "${user_path}-old"
fi
mkdir -p "$user_path"
ln -snvf "$this_path/vscode" "$user_path"

### Install VSCode extensions ##################################################

if command -v code >/dev/null; then
  while read -r extension; do
    code --force --install-extension "$extension"
  done <"$this_path/vscode/extensions.list"
fi
