#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

this_path=$(cd "$(dirname "$0")" && pwd)
dotfiles_path="$this_path/dotfiles"

### Symlink bin ################################################################

local_bin_path="$HOME/local/bin"
if [ -d "$local_bin_path" ] && [ ! -L "$local_bin_path" ]; then
  rm -rf "$HOME/local/bin-old"
  mkdir -pv "$HOME/local" # required for mv target
  mv -v "$local_bin_path" "$HOME/local/bin-old"
fi
mkdir -pv "$HOME/local"
ln -snvf "$this_path/bin" "$local_bin_path"

### Symlink etc ################################################################

local_etc_path="$HOME/local/etc"
if [ -d "$local_etc_path" ] && [ ! -L "$local_etc_path" ]; then
  rm -rf "$HOME/local/etc-old"
  mkdir -pv "$HOME/local" # required for mv target
  mv -v "$local_etc_path" "$HOME/local/etc-old"
fi
mkdir -pv "$HOME/local"
ln -snvf "$this_path/etc" "$local_etc_path"

### Symlink dotfiles ###########################################################

files="$(find "$dotfiles_path" -type f -exec basename {} \;)"

for source_file_name in $files; do
  # backup non-symlink dotfiles
  if [ ! -L "$HOME/$source_file_name" ]; then
    mkdir -pv "$HOME/.dotfiles-old"
    cp -v "$HOME/$source_file_name" "$HOME/.dotfiles-old/$source_file_name"
  fi
  ln -snvf "$dotfiles_path/$source_file_name" "$HOME/$source_file_name"
done

### Symlink Starship config ####################################################

mkdir -pv "$HOME/.config"
# backup non-symlink starship.toml
if [ ! -L "$HOME/.config/starship.toml" ]; then
  mkdir -pv "$HOME/.config-old"
  cp -v "$HOME/.config/starship.toml" "$HOME/.config-old/starship.toml"
fi
ln -snvf "$HOME/local/etc/starship/config.toml" "$HOME/.config/starship.toml"

### Symlink Topgrade config ####################################################

mkdir -pv "$HOME/.config"
# backup non-symlink topgrade.toml
if [ ! -L "$HOME/.config/topgrade.toml" ]; then
  mkdir -pv "$HOME/.config-old"
  cp -v "$HOME/.config/topgrade.toml" "$HOME/.config-old/topgrade.toml"
fi
ln -snvf "$HOME/local/etc/topgrade/topgrade.toml" "$HOME/.config/topgrade.toml"

### Symlink htoprc for Linux distributions #####################################

if [ "$(uname -s)" = 'Linux' ]; then
  mkdir -pv "$HOME/.config/htop"
  # backup non-symlink htoprc
  if [ ! -L "$HOME/.config/htop/htoprc" ]; then
    mkdir -pv "$HOME/.config-old/htop"
    cp -v "$HOME/.config/htop/htoprc" "$HOME/.config-old/htop/htoprc"
  fi
  ln -snvf "$dotfiles_path/.htoprc" "$HOME/.config/htop/htoprc"
fi
