#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

this_path=$(cd "$(dirname "$0")" && pwd)
dotfiles_path="$this_path/dotfiles"
backup_path="$this_path/.backup"

### Symlink bin ################################################################

local_bin_path="$HOME/local/bin"
if [ ! -d "$backup_path/local/bin" ] && [ -d "$local_bin_path" ]; then
  mkdir -p "$backup_path/local"
  cp -RP "$local_bin_path" "$backup_path/local/bin"
fi
mkdir -p "$local_bin_path"
rm -rf "$local_bin_path"
ln -sfnv "$this_path/bin" "$local_bin_path"

### Symlink etc ################################################################

local_etc_path="$HOME/local/etc"
if [ ! -d "$backup_path/local/etc" ] && [ -d "$local_etc_path" ]; then
  mkdir -p "$backup_path/local"
  cp -RP "$local_etc_path" "$backup_path/local/etc"
fi
mkdir -p "$local_etc_path"
rm -rf "$local_etc_path"
ln -sfnv "$this_path/etc" "$local_etc_path"

### Symlink dotfiles ###########################################################

files="$(find "$dotfiles_path" -type f -exec basename {} \;)"

for source_file_name in $files; do
  if [ ! -r "$backup_path/$source_file_name" ]; then
    mkdir -p "$backup_path"
    cp -P "$HOME/$source_file_name" "$backup_path/$source_file_name"
  fi
  ln -sfv "$dotfiles_path/$source_file_name" "$HOME/$source_file_name"
done

### Symlink Starship config ####################################################

if [ ! -r "$backup_path/.config/starship.toml" ]; then
  if [ -r "$HOME/.config/starship.toml" ]; then
    mkdir -p "$backup_path/.config"
    cp -P "$HOME/.config/starship.toml" "$backup_path/.config/starship.toml"
  fi
fi
mkdir -p "$HOME/.config"
ln -sfv "$HOME/local/etc/starship/config.toml" "$HOME/.config/starship.toml"

### Symlink Topgrade config ####################################################

if [ ! -r "$backup_path/.config/topgrade.toml" ]; then
  if [ -r "$$HOME/.config/topgrade.toml" ]; then
    mkdir -p "$backup_path/.config"
    cp -P "$HOME/.config/topgrade.toml" "$backup_path/.config/topgrade.toml"
  fi
fi
mkdir -p "$HOME/.config"
ln -sfv "$HOME/local/etc/topgrade/topgrade.toml" "$HOME/.config/topgrade.toml"

### Symlink htoprc for Linux distributions #####################################

if [ "$(uname -s)" = 'Linux' ]; then
  if [ ! -r "$backup_path/.config/htop/htoprc" ]; then
    if [ -r "$HOME/.config/htop/htoprc" ]; then
      mkdir -p "$backup_path/.config/htop"
      cp -P "$HOME/.config/htop/htoprc" "$backup_path/.config/htop/htoprc"
    fi
  fi
  mkdir -p "$HOME/.config/htop"
  ln -sfv "$dotfiles_path/.htoprc" "$HOME/.config/htop/htoprc"
fi
