#!/usr/bin/env python3
"""Conservative structure map extraction for code rereads.

This module summarizes a narrow set of code files into bounded structural views
that favor safety over completeness. It uses stdlib-only parsing and avoids
subprocess/network access. Unsupported, generated-looking, oversized, or
risky files degrade to a small digest instead of forcing a substitution.
"""

from __future__ import annotations

import ast
import hashlib
import os
import re
from dataclasses import asdict, dataclass
from math import ceil
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

PYTHON_SUFFIX = ".py"
JS_TS_SUFFIXES = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".mts", ".cts"}

LANGUAGE_LABELS = {
    PYTHON_SUFFIX: "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".md": "markdown",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
}

NON_CODE_SUFFIXES = frozenset({".md", ".json", ".yaml", ".yml", ".toml"})

MIN_TOKENS_FOR_STRUCTURE = 1000
MAX_AST_BYTES = 800 * 1024
MAX_AST_LINES = 20000
MAX_JS_TS_BYTES = 400 * 1024
MAX_JS_TS_LINES = 5000

MAX_REPLACEMENT_CHARS = {
    "signatures": 800,
    "top_level": 1200,
    "skeleton": 2400,
    "digest": 900,
}

MAX_SIGNATURE_ITEMS = 12
MAX_TOP_LEVEL_IMPORTS = 10
MAX_TOP_LEVEL_SYMBOLS = 12
MAX_SKELETON_CLASSES = 4
MAX_SKELETON_METHODS_PER_CLASS = 4
MAX_SKELETON_TOP_LEVEL_FUNCTIONS = 8
MAX_SKELETON_TOP_LEVEL_IMPORTS = 8
MAX_SKELETON_TOP_LEVEL_ASSIGNMENTS = 8
MAX_DECORATORS = 2
MAX_BASES = 3
MAX_DOCSTRING_CHARS = 120
MAX_DIGEST_HEAD_LINES = 6
MAX_DIGEST_TAIL_LINES = 6

GENERATED_MARKERS = (
    "generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "this file was generated",
    "code generated",
    "generated file",
    "generated code",
)

JS_TS_METHOD_SKIP = {
    "if",
    "for",
    "while",
    "switch",
    "catch",
    "constructor",
}

JS_TS_EXPORT_PREFIX = re.compile(r"^(?:export\s+)?(?:default\s+)?")
JS_TS_IMPORT_RE = re.compile(
    r"^(?:import\b.*|export\s+\{[^}]+\}\s+from\b.*|export\s+\*\s+from\b.*)$"
)
JS_TS_CLASS_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?(?:abstract\s+)?)class\s+(?P<name>[A-Za-z_$][\w$]*)"
)
JS_TS_INTERFACE_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?)interface\s+(?P<name>[A-Za-z_$][\w$]*)"
)
JS_TS_TYPE_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?)type\s+(?P<name>[A-Za-z_$][\w$]*)\b"
)
JS_TS_ENUM_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?)enum\s+(?P<name>[A-Za-z_$][\w$]*)\b"
)
JS_TS_FUNCTION_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?)(?P<async>async\s+)?function\s+(?P<name>[A-Za-z_$][\w$]*)\s*\("
)
JS_TS_VAR_FUNCTION_RE = re.compile(
    r"^(?P<prefix>(?:export\s+)?(?:default\s+)?)"
    r"(?P<kind>const|let|var)\s+"
    r"(?P<name>[A-Za-z_$][\w$]*)"
    r"(?P<type>\s*:\s*[^=]+)?\s*=\s*"
    r"(?:(?P<async>async)\s+)?(?:(?:function\b)|(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>)"
)
JS_TS_EXPORT_DEFAULT_IDENTIFIER_RE = re.compile(
    r"^export\s+default\s+(?P<name>[A-Za-z_$][\w$]*)\s*;?$"
)
JS_TS_EXPORT_LIST_RE = re.compile(r"^export\s+\{(?P<body>[^}]+)\}(?:\s+from\b.*)?$")
JS_TS_METHOD_RE = re.compile(
    r"^(?:(?:public|private|protected|static|readonly|async|abstract|override|get|set)\s+)*"
    r"(?P<name>[A-Za-z_$][\w$]*)\s*\("
)
JS_TS_PROPERTY_ARROW_RE = re.compile(
    r"^(?:(?:public|private|protected|static|readonly|async|override)\s+)*"
    r"(?P<name>[A-Za-z_$][\w$]*)"
    r"(?:\??\s*:\s*[^=]+)?\s*=\s*(?:async\s+)?(?:\([^)]*\)|[A-Za-z_$][\w$]*)\s*=>"
)


@dataclass(frozen=True)
class StructureMapResult:
    """Result of a conservative structure summary."""

    file_path: str
    language: str
    replacement_type: str
    replacement_text: str
    replacement_tokens_est: int
    confidence: float
    fingerprint: str
    eligible: bool
    reason: str
    generated_like: bool
    parse_ok: bool
    line_count: int
    file_tokens_est: Optional[int] = None
    file_size_bytes: Optional[int] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass(frozen=True)
class _FunctionSummary:
    name: str
    signature: str
    lineno: int
    decorators: Tuple[str, ...]
    is_async: bool


@dataclass(frozen=True)
class _ClassSummary:
    name: str
    signature: str
    lineno: int
    decorators: Tuple[str, ...]
    methods: Tuple[_FunctionSummary, ...]


@dataclass(frozen=True)
class _JsTsSymbolSummary:
    kind: str
    name: str
    signature: str
    lineno: int
    exported: bool = False


def is_python_file(file_path: str | os.PathLike[str]) -> bool:
    """Return True when the path looks like a Python source file."""

    return Path(str(file_path)).suffix.lower() == PYTHON_SUFFIX


def is_js_ts_file(file_path: str | os.PathLike[str]) -> bool:
    """Return True when the path looks like a JS/TS-family source file."""

    return Path(str(file_path)).suffix.lower() in JS_TS_SUFFIXES


def detect_structure_language(file_path: str | os.PathLike[str]) -> str:
    """Return the structure-language label used by summaries."""

    suffix = Path(str(file_path)).suffix.lower()
    return LANGUAGE_LABELS.get(suffix, "unknown")


def is_structure_supported_file(file_path: str | os.PathLike[str]) -> bool:
    """Return True when this module may attempt a structure map."""

    if is_python_file(file_path) or is_js_ts_file(file_path):
        return True
    return Path(str(file_path)).suffix.lower() in NON_CODE_SUFFIXES


def estimate_tokens(text: str) -> int:
    """Estimate tokens via the shared calibrated estimator (U-F).

    Kept as a thin wrapper so existing call sites keep importing
    ``structure_map.estimate_tokens`` unchanged, while the calibration
    constant lives in one place (``token_estimate``). Falls back to the legacy
    4 chars/token ratio only if the shared module is unavailable.
    """

    if not text:
        return 0
    try:
        from token_estimate import estimate_tokens as _shared
        return _shared(text)
    except ImportError:
        return max(1, ceil(len(text) / 4))


def summarize_python_file(
    file_path: str | os.PathLike[str],
    *,
    content: Optional[str] = None,
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    """Summarize a Python file from disk or supplied content.

    The summary is conservative: it only produces structure maps for whole-file
    rereads of Python sources and falls back to a small digest otherwise.
    """

    path = Path(str(file_path))
    source = content
    if source is None:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return _build_fallback_result(
                file_path=str(path),
                language=detect_structure_language(path),
                source="",
                reason="unreadable",
                confidence=0.05,
                parse_ok=False,
                generated_like=False,
                file_tokens_est=file_tokens_est,
                file_size_bytes=file_size_bytes,
            )

    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)

    return summarize_python_source(
        source,
        file_path=str(path),
        offset=offset,
        limit=limit,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def summarize_code_file(
    file_path: str | os.PathLike[str],
    *,
    content: Optional[str] = None,
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    """Summarize a supported code file from disk or supplied content."""

    path = Path(str(file_path))
    source = content
    if source is None:
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            return _build_fallback_result(
                file_path=str(path),
                language=detect_structure_language(path),
                source="",
                reason="unreadable",
                confidence=0.05,
                parse_ok=False,
                generated_like=False,
                file_tokens_est=file_tokens_est,
                file_size_bytes=file_size_bytes,
            )

    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)

    return summarize_code_source(
        source,
        file_path=str(path),
        offset=offset,
        limit=limit,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def summarize_code_source(
    source: str,
    *,
    file_path: str = "memory.py",
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    """Summarize supported code source by language."""

    path = str(file_path)
    if is_python_file(path):
        return summarize_python_source(
            source,
            file_path=path,
            offset=offset,
            limit=limit,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )
    if is_js_ts_file(path):
        return summarize_js_ts_source(
            source,
            file_path=path,
            offset=offset,
            limit=limit,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )
    suffix = Path(path).suffix.lower()
    if suffix in NON_CODE_SUFFIXES:
        return _summarize_non_code_source(
            source,
            file_path=path,
            suffix=suffix,
            offset=offset,
            limit=limit,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )
    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)
    return _build_fallback_result(
        file_path=path,
        language=detect_structure_language(path),
        source=source,
        reason="unsupported_language",
        confidence=0.10,
        parse_ok=False,
        generated_like=False,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def summarize_python_source(
    source: str,
    *,
    file_path: str = "memory.py",
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    """Summarize Python source into a bounded structure map."""

    path = str(file_path)
    line_count = source.count("\n") + (1 if source else 0)
    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)

    if not is_python_file(path):
        return _build_fallback_result(
            file_path=path,
            language=detect_structure_language(path),
            source=source,
            reason="unsupported_language",
            confidence=0.10,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if offset != 0 or limit != 0:
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="partial_range_not_supported",
            confidence=0.12,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if not source.strip():
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="empty_file",
            confidence=0.05,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if file_tokens_est < MIN_TOKENS_FOR_STRUCTURE:
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="below_min_tokens",
            confidence=0.18,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if file_size_bytes > MAX_AST_BYTES or line_count > MAX_AST_LINES:
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="over_ast_caps",
            confidence=0.20,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    generated_like = looks_generated_python(source)
    if generated_like:
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="generated_like",
            confidence=0.16,
            parse_ok=False,
            generated_like=True,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    try:
        tree = ast.parse(source, filename=path)
        parse_ok = True
    except (SyntaxError, ValueError, RecursionError, MemoryError):
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="ast_parse_failed",
            confidence=0.14,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    module_docstring = ast.get_docstring(tree, clean=False)
    top_level_imports, top_level_classes, top_level_functions, top_level_assignments = _collect_module_structure(tree)
    total_methods = sum(len(cls.methods) for cls in top_level_classes)
    replacement_type = _choose_replacement_type(
        file_tokens_est=file_tokens_est,
        line_count=line_count,
        class_count=len(top_level_classes),
        function_count=len(top_level_functions),
        assignment_count=len(top_level_assignments),
        method_count=total_methods,
    )

    rendered = _render_candidate(
        replacement_type,
        path=path,
        line_count=line_count,
        module_docstring=module_docstring,
        imports=top_level_imports,
        classes=top_level_classes,
        functions=top_level_functions,
        assignments=top_level_assignments,
    )

    if len(rendered) > MAX_REPLACEMENT_CHARS[replacement_type]:
        rendered, replacement_type = _shrink_or_fallback(
            path=path,
            line_count=line_count,
            module_docstring=module_docstring,
            imports=top_level_imports,
            classes=top_level_classes,
            functions=top_level_functions,
            assignments=top_level_assignments,
            preferred=replacement_type,
        )

    if len(rendered) > MAX_REPLACEMENT_CHARS[replacement_type]:
        return _build_fallback_result(
            file_path=path,
            language="python",
            source=source,
            reason="structure_over_cap",
            confidence=0.22,
            parse_ok=parse_ok,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    eligible = replacement_type != "digest"
    reason = "ok" if eligible else "fallback_digest"

    confidence = _score_confidence(
        replacement_type=replacement_type,
        line_count=line_count,
        file_tokens_est=file_tokens_est,
        class_count=len(top_level_classes),
        function_count=len(top_level_functions),
        method_count=total_methods,
        rendered_len=len(rendered),
        parse_ok=parse_ok,
        generated_like=False,
    )

    fingerprint = _fingerprint(
        path=path,
        replacement_type=replacement_type,
        rendered=rendered,
        line_count=line_count,
        file_size_bytes=file_size_bytes,
    )

    return StructureMapResult(
        file_path=path,
        language="python",
        replacement_type=replacement_type,
        replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=confidence,
        fingerprint=fingerprint,
        eligible=eligible,
        reason=reason,
        generated_like=False,
        parse_ok=parse_ok,
        line_count=line_count,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def summarize_js_ts_source(
    source: str,
    *,
    file_path: str = "memory.ts",
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    """Summarize JS/TS-family source into a bounded structure map."""

    path = str(file_path)
    language = detect_structure_language(path)
    line_count = source.count("\n") + (1 if source else 0)
    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)

    if not is_js_ts_file(path):
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="unsupported_language",
            confidence=0.10,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if offset != 0 or limit != 0:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="partial_range_not_supported",
            confidence=0.12,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if not source.strip():
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="empty_file",
            confidence=0.05,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if file_tokens_est < MIN_TOKENS_FOR_STRUCTURE:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="below_min_tokens",
            confidence=0.20,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    if file_size_bytes > MAX_JS_TS_BYTES or line_count > MAX_JS_TS_LINES:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="over_ast_caps",
            confidence=0.22,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    generated_like = looks_generated_js_ts(source)
    if generated_like:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="generated_like",
            confidence=0.18,
            parse_ok=False,
            generated_like=True,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    imports, classes, functions, symbols = _collect_js_ts_structure(source)
    if not imports and not classes and not functions and not symbols:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="low_signal_structure",
            confidence=0.24,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    replacement_type = _choose_js_ts_replacement_type(
        file_tokens_est=file_tokens_est,
        line_count=line_count,
        class_count=len(classes),
        function_count=len(functions),
        symbol_count=len(symbols),
        method_count=sum(len(cls.methods) for cls in classes),
    )
    rendered = _render_js_ts_candidate(
        language=language,
        replacement_type=replacement_type,
        line_count=line_count,
        imports=imports,
        classes=classes,
        functions=functions,
        symbols=symbols,
    )

    if len(rendered) > MAX_REPLACEMENT_CHARS[replacement_type]:
        rendered, replacement_type = _shrink_js_ts_or_fallback(
            language=language,
            line_count=line_count,
            imports=imports,
            classes=classes,
            functions=functions,
            symbols=symbols,
            preferred=replacement_type,
        )

    if len(rendered) > MAX_REPLACEMENT_CHARS[replacement_type]:
        return _build_fallback_result(
            file_path=path,
            language=language,
            source=source,
            reason="structure_over_cap",
            confidence=0.24,
            parse_ok=False,
            generated_like=False,
            file_tokens_est=file_tokens_est,
            file_size_bytes=file_size_bytes,
        )

    confidence = _score_js_ts_confidence(
        replacement_type=replacement_type,
        line_count=line_count,
        file_tokens_est=file_tokens_est,
        class_count=len(classes),
        function_count=len(functions),
        symbol_count=len(symbols),
        method_count=sum(len(cls.methods) for cls in classes),
        rendered_len=len(rendered),
    )

    return StructureMapResult(
        file_path=path,
        language=language,
        replacement_type=replacement_type,
        replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=confidence,
        fingerprint=_fingerprint(
            path=path,
            replacement_type=replacement_type,
            rendered=rendered,
            line_count=line_count,
            file_size_bytes=file_size_bytes,
        ),
        eligible=replacement_type != "digest",
        reason="ok" if replacement_type != "digest" else "fallback_digest",
        generated_like=False,
        parse_ok=False,
        line_count=line_count,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def looks_generated_js_ts(source: str) -> bool:
    """Heuristically detect generated or bundled JS/TS source."""

    lower = source[:5000].lower()
    for marker in GENERATED_MARKERS:
        if marker in lower:
            return True

    lines = [line for line in source.splitlines() if line.strip()]
    if len(lines) < 20:
        return False

    unique_lines = len(set(lines))
    repeated_ratio = 1.0 - (unique_lines / len(lines))
    average_len = sum(len(line) for line in lines) / len(lines)
    long_line_ratio = sum(1 for line in lines if len(line) > 260) / len(lines)

    if repeated_ratio >= 0.35 and len(lines) >= 80:
        return True
    if average_len >= 220 and long_line_ratio >= 0.30:
        return True
    return False


def _collect_js_ts_structure(
    source: str,
) -> Tuple[Tuple[str, ...], Tuple[_ClassSummary, ...], Tuple[_FunctionSummary, ...], Tuple[_JsTsSymbolSummary, ...]]:
    raw_lines = source.splitlines()
    clean_lines = _strip_js_ts_comments_and_strings(source).splitlines()

    imports: List[str] = []
    classes: List[_ClassSummary] = []
    functions: List[_FunctionSummary] = []
    symbols: List[_JsTsSymbolSummary] = []

    depth = 0
    current_class_index: Optional[int] = None
    current_class_body_depth: Optional[int] = None

    for lineno, (raw_line, clean_line) in enumerate(zip(raw_lines, clean_lines), 1):
        clean = clean_line.strip()
        raw = raw_line.strip()
        if not clean:
            depth = max(0, depth + clean_line.count("{") - clean_line.count("}"))
            if current_class_index is not None and depth < (current_class_body_depth or 0):
                current_class_index = None
                current_class_body_depth = None
            continue

        if depth == 0:
            if JS_TS_IMPORT_RE.match(clean):
                imports.append(_normalize_js_ts_signature(raw))
            else:
                class_summary = _match_js_ts_class(clean, raw, lineno)
                if class_summary is not None:
                    classes.append(class_summary)
                    current_class_index = len(classes) - 1
                else:
                    function_summary = _match_js_ts_function(clean, raw, lineno)
                    if function_summary is not None:
                        functions.append(function_summary)
                    else:
                        symbol_summary = _match_js_ts_symbol(clean, raw, lineno)
                        if symbol_summary is not None:
                            symbols.append(symbol_summary)

        elif current_class_index is not None and depth == current_class_body_depth:
            method = _match_js_ts_method(clean, raw, lineno, classes[current_class_index].name)
            if method is not None:
                updated_methods = list(classes[current_class_index].methods)
                updated_methods.append(method)
                classes[current_class_index] = _ClassSummary(
                    name=classes[current_class_index].name,
                    signature=classes[current_class_index].signature,
                    lineno=classes[current_class_index].lineno,
                    decorators=(),
                    methods=tuple(updated_methods),
                )

        next_depth = max(0, depth + clean_line.count("{") - clean_line.count("}"))
        if current_class_index is not None and depth == 0 and next_depth > depth:
            current_class_body_depth = next_depth
        if current_class_index is not None and next_depth < (current_class_body_depth or 0):
            current_class_index = None
            current_class_body_depth = None
        depth = next_depth

    return (
        tuple(dict.fromkeys(imports)),
        tuple(classes),
        tuple(functions),
        tuple(_dedupe_js_ts_symbols(symbols)),
    )


def _strip_js_ts_comments_and_strings(source: str) -> str:
    NORMAL = 0
    LINE_COMMENT = 1
    BLOCK_COMMENT = 2
    SINGLE_QUOTE = 3
    DOUBLE_QUOTE = 4
    TEMPLATE = 5

    state = NORMAL
    escaped = False
    out: List[str] = []

    for index, char in enumerate(source):
        nxt = source[index + 1] if index + 1 < len(source) else ""
        if state == LINE_COMMENT:
            if char == "\n":
                state = NORMAL
                out.append("\n")
            else:
                out.append(" ")
            continue
        if state == BLOCK_COMMENT:
            if char == "*" and nxt == "/":
                out.extend("  ")
                state = NORMAL
                continue
            out.append("\n" if char == "\n" else " ")
            continue
        if state in {SINGLE_QUOTE, DOUBLE_QUOTE, TEMPLATE}:
            if char == "\n" and state != TEMPLATE:
                state = NORMAL
                out.append("\n")
                escaped = False
                continue
            if escaped:
                out.append(" ")
                escaped = False
                continue
            if char == "\\":
                out.append(" ")
                escaped = True
                continue
            if (state == SINGLE_QUOTE and char == "'") or (
                state == DOUBLE_QUOTE and char == '"'
            ) or (state == TEMPLATE and char == "`"):
                state = NORMAL
                out.append(" ")
                continue
            out.append("\n" if char == "\n" else " ")
            continue

        if char == "/" and nxt == "/":
            out.extend("  ")
            state = LINE_COMMENT
            continue
        if char == "/" and nxt == "*":
            out.extend("  ")
            state = BLOCK_COMMENT
            continue
        if char == "'":
            out.append(" ")
            state = SINGLE_QUOTE
            continue
        if char == '"':
            out.append(" ")
            state = DOUBLE_QUOTE
            continue
        if char == "`":
            out.append(" ")
            state = TEMPLATE
            continue
        out.append(char)

    return "".join(out)


def _match_js_ts_class(clean: str, raw: str, lineno: int) -> Optional[_ClassSummary]:
    match = JS_TS_CLASS_RE.match(clean)
    if not match:
        return None
    exported = clean.startswith("export ")
    signature = _normalize_js_ts_signature(raw, fallback=f"class {match.group('name')}")
    if exported and not signature.startswith("export "):
        signature = "export " + signature
    return _ClassSummary(
        name=match.group("name"),
        signature=signature,
        lineno=lineno,
        decorators=(),
        methods=(),
    )


def _match_js_ts_function(clean: str, raw: str, lineno: int) -> Optional[_FunctionSummary]:
    match = JS_TS_FUNCTION_RE.match(clean)
    if match:
        exported = bool(match.group("prefix").strip())
        signature = _normalize_js_ts_signature(raw, fallback=f"function {match.group('name')}(...)")
        if exported and not signature.startswith("export "):
            signature = "export " + signature
        return _FunctionSummary(
            name=match.group("name"),
            signature=signature,
            lineno=lineno,
            decorators=(),
            is_async=bool(match.group("async")),
        )

    match = JS_TS_VAR_FUNCTION_RE.match(clean)
    if not match:
        return None
    exported = bool(match.group("prefix").strip())
    prefix = f"{match.group('kind')} {match.group('name')}"
    if match.group("type"):
        prefix += ": " + " ".join(match.group("type").split()).lstrip(":").strip()
    if "=>" in clean:
        prefix += " = (...) =>"
    else:
        prefix += " = function(...)"
    if exported:
        prefix = "export " + prefix
    return _FunctionSummary(
        name=match.group("name"),
        signature=prefix,
        lineno=lineno,
        decorators=(),
        is_async=bool(match.group("async")),
    )


def _match_js_ts_symbol(clean: str, raw: str, lineno: int) -> Optional[_JsTsSymbolSummary]:
    for regex, kind in (
        (JS_TS_INTERFACE_RE, "interface"),
        (JS_TS_TYPE_RE, "type"),
        (JS_TS_ENUM_RE, "enum"),
    ):
        match = regex.match(clean)
        if match:
            exported = bool(match.group("prefix").strip())
            signature = _normalize_js_ts_signature(raw, fallback=f"{kind} {match.group('name')}")
            if exported and not signature.startswith("export "):
                signature = "export " + signature
            return _JsTsSymbolSummary(
                kind=kind,
                name=match.group("name"),
                signature=signature,
                lineno=lineno,
                exported=exported,
            )

    match = JS_TS_EXPORT_DEFAULT_IDENTIFIER_RE.match(clean)
    if match:
        return _JsTsSymbolSummary(
            kind="export",
            name=match.group("name"),
            signature=f"export default {match.group('name')}",
            lineno=lineno,
            exported=True,
        )

    match = JS_TS_EXPORT_LIST_RE.match(clean)
    if match:
        body = ", ".join(part.strip() for part in match.group("body").split(",") if part.strip())
        if body:
            return _JsTsSymbolSummary(
                kind="export",
                name=body.split(",")[0],
                signature=f"export {{ {body} }}",
                lineno=lineno,
                exported=True,
            )
    return None


def _match_js_ts_method(
    clean: str,
    raw: str,
    lineno: int,
    owner: str,
) -> Optional[_FunctionSummary]:
    method_match = JS_TS_METHOD_RE.match(clean)
    if method_match:
        name = method_match.group("name")
        if name not in JS_TS_METHOD_SKIP:
            return _FunctionSummary(
                name=name,
                signature=f"{owner}.{_normalize_js_ts_signature(raw, fallback=f'{name}(...)')}",
                lineno=lineno,
                decorators=(),
                is_async="async " in clean,
            )

    arrow_match = JS_TS_PROPERTY_ARROW_RE.match(clean)
    if arrow_match:
        name = arrow_match.group("name")
        if name not in JS_TS_METHOD_SKIP:
            return _FunctionSummary(
                name=name,
                signature=f"{owner}.{name} = (...) =>",
                lineno=lineno,
                decorators=(),
                is_async="async " in clean,
            )
    return None


def _render_js_ts_candidate(
    *,
    language: str,
    replacement_type: str,
    line_count: int,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    symbols: Sequence[_JsTsSymbolSummary],
) -> str:
    sections: List[str] = [f"{language} {replacement_type}", f"lines: {line_count}"]
    if replacement_type == "skeleton":
        sections.extend(
            _render_js_ts_skeleton(
                imports=imports,
                classes=classes,
                functions=functions,
                symbols=symbols,
            )
        )
    elif replacement_type == "top_level":
        sections.extend(
            _render_js_ts_top_level(
                imports=imports,
                classes=classes,
                functions=functions,
                symbols=symbols,
            )
        )
    elif replacement_type == "signatures":
        sections.extend(
            _render_js_ts_signatures(
                imports=imports,
                classes=classes,
                functions=functions,
                symbols=symbols,
            )
        )
    else:
        sections.extend(_render_digest_lines(path="memory", line_count=line_count))
    return "\n".join(section for section in sections if section)


def _render_js_ts_skeleton(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    symbols: Sequence[_JsTsSymbolSummary],
) -> List[str]:
    lines: List[str] = []
    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_JS_TS_IMPORTS):
            lines.append(f"  - {item}")
    if classes:
        lines.append(f"classes ({len(classes)}):")
        for cls in _shorten_list(classes, MAX_SKELETON_CLASSES):
            lines.append(f"  - {cls.signature} @ L{cls.lineno}")
            if cls.methods:
                lines.append("    methods:")
                for method in _shorten_list(cls.methods, MAX_SKELETON_METHODS_PER_CLASS):
                    lines.append(f"      - {_strip_signature_prefix(method.signature)} @ L{method.lineno}")
    if functions:
        lines.append(f"functions ({len(functions)}):")
        for func in _shorten_list(functions, MAX_JS_TS_SKELETON_FUNCTIONS):
            lines.append(f"  - {func.signature} @ L{func.lineno}")
    if symbols:
        lines.append(f"types/exports ({len(symbols)}):")
        for symbol in _shorten_list(symbols, MAX_JS_TS_SKELETON_SYMBOLS):
            lines.append(f"  - {symbol.signature} @ L{symbol.lineno}")
    return lines


def _render_js_ts_top_level(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    symbols: Sequence[_JsTsSymbolSummary],
) -> List[str]:
    lines: List[str] = []
    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_JS_TS_IMPORTS):
            lines.append(f"  - {item}")

    symbol_lines: List[str] = [f"{cls.signature} @ L{cls.lineno}" for cls in classes]
    symbol_lines.extend(f"{func.signature} @ L{func.lineno}" for func in functions)
    symbol_lines.extend(f"{symbol.signature} @ L{symbol.lineno}" for symbol in symbols)
    if symbol_lines:
        lines.append(f"symbols ({len(symbol_lines)}):")
        for item in _shorten_list(symbol_lines, MAX_JS_TS_TOP_LEVEL_SYMBOLS):
            lines.append(f"  - {item}")
    return lines


def _render_js_ts_signatures(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    symbols: Sequence[_JsTsSymbolSummary],
) -> List[str]:
    lines: List[str] = []
    items: List[str] = []
    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_JS_TS_IMPORTS):
            lines.append(f"  - {item}")
    for cls in classes:
        items.append(f"{cls.signature} @ L{cls.lineno}")
        for method in cls.methods:
            items.append(f"{_strip_signature_prefix(method.signature)} @ L{method.lineno}")
    for func in functions:
        items.append(f"{func.signature} @ L{func.lineno}")
    for symbol in symbols:
        items.append(f"{symbol.signature} @ L{symbol.lineno}")
    if items:
        lines.append(f"signatures ({len(items)}):")
        for item in _shorten_list(items, MAX_JS_TS_SIGNATURE_ITEMS):
            lines.append(f"  - {item}")
    return lines


def _choose_js_ts_replacement_type(
    *,
    file_tokens_est: int,
    line_count: int,
    class_count: int,
    function_count: int,
    symbol_count: int,
    method_count: int,
) -> str:
    total_symbols = class_count + function_count + symbol_count
    large_file = file_tokens_est >= 3200 or line_count >= 850 or total_symbols >= 18
    moderate_file = file_tokens_est >= 1500 or line_count >= 220 or total_symbols >= 8
    if class_count > 0 and method_count > 0 and moderate_file:
        return "skeleton"
    if large_file:
        return "signatures"
    if total_symbols <= 6 and line_count <= 180:
        return "top_level"
    if class_count > 0 and moderate_file:
        return "skeleton"
    if total_symbols <= 12:
        return "top_level"
    return "signatures"


def _shrink_js_ts_or_fallback(
    *,
    language: str,
    line_count: int,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    symbols: Sequence[_JsTsSymbolSummary],
    preferred: str,
) -> Tuple[str, str]:
    order = {
        "skeleton": ["skeleton", "top_level", "signatures", "digest"],
        "top_level": ["top_level", "signatures", "digest"],
        "signatures": ["signatures", "top_level", "digest"],
        "digest": ["digest"],
    }.get(preferred, ["digest"])

    for replacement_type in order:
        rendered = _render_js_ts_candidate(
            language=language,
            replacement_type=replacement_type,
            line_count=line_count,
            imports=imports,
            classes=classes,
            functions=functions,
            symbols=symbols,
        )
        if len(rendered) <= MAX_REPLACEMENT_CHARS[replacement_type]:
            return rendered, replacement_type

    rendered = _render_digest_lines(path="memory", line_count=line_count)
    return "\n".join(rendered), "digest"


def _score_js_ts_confidence(
    *,
    replacement_type: str,
    line_count: int,
    file_tokens_est: int,
    class_count: int,
    function_count: int,
    symbol_count: int,
    method_count: int,
    rendered_len: int,
) -> float:
    base = {
        "skeleton": 0.89,
        "top_level": 0.95,
        "signatures": 0.90,
        "digest": 0.30,
    }.get(replacement_type, 0.35)
    if file_tokens_est >= 4500:
        base -= 0.02
    if line_count >= 1200:
        base -= 0.02
    if class_count >= 4:
        base -= 0.02
    if method_count >= 10:
        base -= 0.02
    if function_count >= 14:
        base -= 0.02
    if symbol_count >= 16:
        base -= 0.01
    if rendered_len >= MAX_REPLACEMENT_CHARS.get(replacement_type, rendered_len):
        base -= 0.04
    return round(max(0.05, min(0.96, base)), 3)


def _normalize_js_ts_signature(raw: str, fallback: Optional[str] = None) -> str:
    compact = " ".join(raw.strip().rstrip("{").rstrip(";").split())
    if not compact:
        return fallback or "..."
    if compact.startswith("import "):
        compact = _compress_js_ts_import(compact)
    elif compact.startswith("export {"):
        compact = _compress_js_ts_export_list(compact)
    if len(compact) <= 120:
        return compact
    return compact[:119] + "…"


def _compress_js_ts_import(compact: str) -> str:
    module_match = re.search(r"\sfrom\s+(['\"][^'\"]+['\"])", compact)
    module = f" from {module_match.group(1)}" if module_match else ""
    if compact.startswith("import * as "):
        left = compact.split(" from ", 1)[0]
        return left + module
    brace_match = re.match(r"import\s+\{(?P<body>[^}]+)\}", compact)
    if brace_match:
        names = [part.strip() for part in brace_match.group("body").split(",") if part.strip()]
        preview = ", ".join(names[:3])
        if len(names) > 3:
            preview += ", …"
        return f"import {{ {preview} }}{module}"
    return compact


def _compress_js_ts_export_list(compact: str) -> str:
    match = JS_TS_EXPORT_LIST_RE.match(compact)
    if not match:
        return compact
    names = [part.strip() for part in match.group("body").split(",") if part.strip()]
    preview = ", ".join(names[:4])
    if len(names) > 4:
        preview += ", …"
    suffix = ""
    if " from " in compact:
        suffix = compact[compact.index(" from ") :]
    return f"export {{ {preview} }}{suffix}"


def _dedupe_js_ts_symbols(symbols: Sequence[_JsTsSymbolSummary]) -> List[_JsTsSymbolSummary]:
    seen = set()
    deduped: List[_JsTsSymbolSummary] = []
    for symbol in symbols:
        key = (symbol.kind, symbol.name, symbol.signature)
        if key in seen:
            continue
        seen.add(key)
        deduped.append(symbol)
    return deduped


def looks_generated_python(source: str) -> bool:
    """Heuristically detect generated or minified-looking Python source."""

    lower = source[:4000].lower()
    for marker in GENERATED_MARKERS:
        if marker in lower:
            return True

    lines = [line for line in source.splitlines() if line.strip()]
    if len(lines) < 20:
        return False

    unique_lines = len(set(lines))
    repeated_ratio = 1.0 - (unique_lines / len(lines))
    average_len = sum(len(line) for line in lines) / len(lines)
    long_line_ratio = sum(1 for line in lines if len(line) > 240) / len(lines)
    comment_ratio = sum(1 for line in lines if line.lstrip().startswith("#")) / len(lines)

    if repeated_ratio >= 0.35 and len(lines) >= 80:
        return True
    if average_len >= 200 and long_line_ratio >= 0.30:
        return True
    if len(lines) >= 150 and comment_ratio <= 0.05 and average_len >= 120 and repeated_ratio >= 0.20:
        return True
    return False


def _collect_module_structure(
    tree: ast.Module,
) -> Tuple[Tuple[str, ...], Tuple[_ClassSummary, ...], Tuple[_FunctionSummary, ...], Tuple[str, ...]]:
    imports: List[str] = []
    classes: List[_ClassSummary] = []
    functions: List[_FunctionSummary] = []
    assignments: List[str] = []

    for node in tree.body:
        if isinstance(node, ast.Import):
            imports.append(_render_import(node))
        elif isinstance(node, ast.ImportFrom):
            imports.append(_render_import_from(node))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            functions.append(_summarize_function(node, owner=None))
        elif isinstance(node, ast.ClassDef):
            classes.append(_summarize_class(node))
        elif isinstance(node, ast.Assign):
            assignments.extend(_summarize_assign(node))
        elif isinstance(node, ast.AnnAssign):
            assignments.extend(_summarize_ann_assign(node))

    return (
        tuple(imports),
        tuple(classes),
        tuple(functions),
        tuple(assignments),
    )


def _summarize_class(node: ast.ClassDef) -> _ClassSummary:
    bases = tuple(_shorten_list([_render_expr(expr) for expr in node.bases], MAX_BASES))
    decorators = tuple(_shorten_list([_render_expr(expr) for expr in node.decorator_list], MAX_DECORATORS))
    methods: List[_FunctionSummary] = []

    for child in node.body:
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            methods.append(_summarize_function(child, owner=node.name))
        elif isinstance(child, ast.ClassDef):
            # Nested classes are intentionally not expanded in v1.
            continue

    signature = _build_class_signature(node.name, bases=bases, decorators=decorators)
    return _ClassSummary(
        name=node.name,
        signature=signature,
        lineno=getattr(node, "lineno", 1),
        decorators=decorators,
        methods=tuple(methods),
    )


def _summarize_function(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    owner: Optional[str],
) -> _FunctionSummary:
    signature = _build_function_signature(node, owner=owner)
    decorators = tuple(_shorten_list([_render_expr(expr) for expr in node.decorator_list], MAX_DECORATORS))
    return _FunctionSummary(
        name=node.name,
        signature=signature,
        lineno=getattr(node, "lineno", 1),
        decorators=decorators,
        is_async=isinstance(node, ast.AsyncFunctionDef),
    )


def _summarize_assign(node: ast.Assign) -> List[str]:
    targets: List[str] = []
    for target in node.targets:
        targets.extend(_flatten_targets(target))

    if any(target == "__all__" for target in targets):
        export_names = _extract_all_export_names(node.value)
        if export_names:
            return [f"__all__ = {', '.join(export_names)}"]
        return ["__all__"]

    rendered: List[str] = []
    for target in targets:
        if _is_public_symbol(target):
            rendered.append(f"{target}")

    return rendered


def _summarize_ann_assign(node: ast.AnnAssign) -> List[str]:
    target_names = _flatten_targets(node.target)
    rendered: List[str] = []
    for target in target_names:
        if _is_public_symbol(target):
            rendered.append(f"{target}")
    return rendered


def _extract_all_export_names(value: ast.AST) -> List[str]:
    names: List[str] = []
    sequence: Optional[Sequence[ast.AST]] = None

    if isinstance(value, (ast.List, ast.Tuple)):
        sequence = value.elts
    elif isinstance(value, ast.Set):
        sequence = value.elts

    if sequence is None:
        return names

    for item in sequence:
        if isinstance(item, ast.Constant) and isinstance(item.value, str):
            names.append(item.value)
        else:
            rendered = _render_expr(item)
            if rendered:
                names.append(rendered)
    return names[:10]


def _render_candidate(
    replacement_type: str,
    *,
    path: str,
    line_count: int,
    module_docstring: Optional[str],
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    assignments: Sequence[str],
) -> str:
    sections: List[str] = [f"python {replacement_type}", f"lines: {line_count}"]

    doc = _short_docstring(module_docstring)
    if doc:
        sections.append(f"docstring: {doc}")

    if replacement_type == "skeleton":
        sections.extend(
            _render_skeleton(
                imports=imports,
                classes=classes,
                functions=functions,
                assignments=assignments,
            )
        )
    elif replacement_type == "top_level":
        sections.extend(
            _render_top_level(
                imports=imports,
                classes=classes,
                functions=functions,
                assignments=assignments,
            )
        )
    elif replacement_type == "signatures":
        sections.extend(
            _render_signatures(
                imports=imports,
                classes=classes,
                functions=functions,
                assignments=assignments,
            )
        )
    else:
        sections.extend(_render_digest_lines(path=path, line_count=line_count))

    return "\n".join(section for section in sections if section)


def _render_skeleton(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    assignments: Sequence[str],
) -> List[str]:
    lines: List[str] = []

    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_SKELETON_TOP_LEVEL_IMPORTS):
            lines.append(f"  - {item}")

    if classes:
        lines.append(f"classes ({len(classes)}):")
        for cls in _shorten_list(classes, MAX_SKELETON_CLASSES):
            lines.append(f"  - {cls.signature} @ L{cls.lineno}")
            if cls.methods:
                lines.append("    methods:")
                for method in _shorten_list(cls.methods, MAX_SKELETON_METHODS_PER_CLASS):
                    lines.append(f"      - {_strip_signature_prefix(method.signature)} @ L{method.lineno}")

    if functions:
        lines.append(f"functions ({len(functions)}):")
        for func in _shorten_list(functions, MAX_SKELETON_TOP_LEVEL_FUNCTIONS):
            lines.append(f"  - {func.signature} @ L{func.lineno}")

    if assignments:
        lines.append(f"assignments ({len(assignments)}):")
        for item in _shorten_list(assignments, MAX_SKELETON_TOP_LEVEL_ASSIGNMENTS):
            lines.append(f"  - {item}")

    return lines


def _render_top_level(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    assignments: Sequence[str],
) -> List[str]:
    lines: List[str] = []

    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_TOP_LEVEL_IMPORTS):
            lines.append(f"  - {item}")

    symbol_lines: List[str] = []
    for cls in classes:
        symbol_lines.append(f"{cls.signature} @ L{cls.lineno}")
    for func in functions:
        symbol_lines.append(f"{func.signature} @ L{func.lineno}")
    for item in assignments:
        symbol_lines.append(f"assign {item}")

    if symbol_lines:
        lines.append(f"symbols ({len(symbol_lines)}):")
        for item in _shorten_list(symbol_lines, MAX_TOP_LEVEL_SYMBOLS):
            lines.append(f"  - {item}")

    return lines


def _render_signatures(
    *,
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    assignments: Sequence[str],
) -> List[str]:
    lines: List[str] = []
    items: List[str] = []

    if imports:
        lines.append(f"imports ({len(imports)}):")
        for item in _shorten_list(imports, MAX_SKELETON_TOP_LEVEL_IMPORTS):
            lines.append(f"  - {item}")

    for cls in classes:
        items.append(f"{cls.signature} @ L{cls.lineno}")
        for method in cls.methods:
            items.append(f"{_strip_signature_prefix(method.signature)} @ L{method.lineno}")
    for func in functions:
        items.append(f"{func.signature} @ L{func.lineno}")
    for item in assignments:
        items.append(f"assign {item}")

    if items:
        lines.append(f"signatures ({len(items)}):")
        for item in _shorten_list(items, MAX_SIGNATURE_ITEMS):
            lines.append(f"  - {item}")

    return lines


def _render_digest_lines(*, path: str, line_count: int) -> List[str]:
    lines = [f"digest fallback for {Path(path).name or path}"]
    lines.append(f"lines: {line_count}")
    return lines


def _strip_signature_prefix(signature: str) -> str:
    if signature.startswith("async def "):
        return "async " + signature[len("async def ") :]
    if signature.startswith("def "):
        return signature[len("def ") :]
    return signature


def _render_import(node: ast.Import) -> str:
    parts = []
    for alias in node.names:
        if alias.asname:
            parts.append(f"{alias.name} as {alias.asname}")
        else:
            parts.append(alias.name)
    return f"import {', '.join(parts)}"


def _render_import_from(node: ast.ImportFrom) -> str:
    module = "." * node.level + (node.module or "")
    parts = []
    for alias in node.names:
        if alias.asname:
            parts.append(f"{alias.name} as {alias.asname}")
        else:
            parts.append(alias.name)
    return f"from {module} import {', '.join(parts)}"


def _build_class_signature(name: str, *, bases: Sequence[str], decorators: Sequence[str]) -> str:
    parts = []
    if decorators:
        parts.append(f"decorators={','.join(decorators)}")
    if bases:
        parts.append(f"bases={','.join(bases)}")
    if parts:
        return f"class {name} ({'; '.join(parts)})"
    return f"class {name}"


def _build_function_signature(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    *,
    owner: Optional[str],
) -> str:
    prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
    name = f"{owner}.{node.name}" if owner else node.name
    args = _render_arguments(node.args)
    signature = f"{prefix} {name}({args})"
    if node.returns is not None:
        signature += f" -> {_render_expr(node.returns)}"
    if node.decorator_list:
        decorators = _shorten_list([_render_expr(expr) for expr in node.decorator_list], MAX_DECORATORS)
        if decorators:
            signature += f" [decorators: {', '.join(decorators)}]"
    return signature


def _render_arguments(args: ast.arguments) -> str:
    rendered: List[str] = []
    positional = list(args.posonlyargs) + list(args.args)
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)

    for index, arg in enumerate(args.posonlyargs):
        rendered.append(_render_single_arg(arg, defaults[index]))
    if args.posonlyargs:
        rendered.append("/")

    offset = len(args.posonlyargs)
    for index, arg in enumerate(args.args):
        rendered.append(_render_single_arg(arg, defaults[offset + index]))

    if args.vararg is not None:
        rendered.append("*" + _render_arg_name(args.vararg))
    elif args.kwonlyargs:
        rendered.append("*")

    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        rendered.append(_render_single_arg(arg, default))

    if args.kwarg is not None:
        rendered.append("**" + _render_arg_name(args.kwarg))

    return ", ".join(part for part in rendered if part)


def _render_single_arg(arg: ast.arg, default: Optional[ast.expr]) -> str:
    rendered = _render_arg_name(arg)
    if arg.annotation is not None:
        rendered += f": {_render_expr(arg.annotation)}"
    if default is not None:
        rendered += f"={_render_expr(default)}"
    return rendered


def _render_arg_name(arg: ast.arg) -> str:
    return arg.arg


def _render_expr(node: ast.AST) -> str:
    if hasattr(ast, "unparse"):
        try:
            return ast.unparse(node)
        except Exception:
            pass
    return _fallback_render_expr(node)


def _fallback_render_expr(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return f"{_fallback_render_expr(node.value)}.{node.attr}"
    if isinstance(node, ast.Constant):
        return repr(node.value)
    if isinstance(node, ast.Subscript):
        return f"{_fallback_render_expr(node.value)}[{_fallback_render_expr(node.slice)}]"
    if isinstance(node, ast.Tuple):
        return ", ".join(_fallback_render_expr(item) for item in node.elts)
    if isinstance(node, ast.List):
        return "[" + ", ".join(_fallback_render_expr(item) for item in node.elts) + "]"
    if isinstance(node, ast.Dict):
        pairs = []
        for key, value in zip(node.keys, node.values):
            if key is None:
                pairs.append("**" + _fallback_render_expr(value))
            else:
                pairs.append(f"{_fallback_render_expr(key)}: {_fallback_render_expr(value)}")
        return "{" + ", ".join(pairs) + "}"
    if isinstance(node, ast.BinOp):
        return f"{_fallback_render_expr(node.left)} {_fallback_operator(node.op)} {_fallback_render_expr(node.right)}"
    if isinstance(node, ast.UnaryOp):
        return f"{_fallback_unary_operator(node.op)}{_fallback_render_expr(node.operand)}"
    if isinstance(node, ast.Call):
        args = [_fallback_render_expr(arg) for arg in node.args]
        kwargs = []
        for kw in node.keywords:
            if kw.arg is None:
                kwargs.append("**" + _fallback_render_expr(kw.value))
            else:
                kwargs.append(f"{kw.arg}={_fallback_render_expr(kw.value)}")
        all_args = args + kwargs
        return f"{_fallback_render_expr(node.func)}({', '.join(all_args)})"
    if isinstance(node, ast.JoinedStr):
        return "f" + repr("".join(_fallback_render_expr(value) for value in node.values))
    if isinstance(node, ast.FormattedValue):
        return "{" + _fallback_render_expr(node.value) + "}"
    return getattr(node, "id", getattr(node, "attr", node.__class__.__name__))


def _fallback_operator(op: ast.AST) -> str:
    mapping = {
        ast.Add: "+",
        ast.Sub: "-",
        ast.Mult: "*",
        ast.MatMult: "@",
        ast.Div: "/",
        ast.FloorDiv: "//",
        ast.Mod: "%",
        ast.Pow: "**",
        ast.LShift: "<<",
        ast.RShift: ">>",
        ast.BitOr: "|",
        ast.BitXor: "^",
        ast.BitAnd: "&",
        ast.And: "and",
        ast.Or: "or",
    }
    for cls, symbol in mapping.items():
        if isinstance(op, cls):
            return symbol
    return "?"


def _fallback_unary_operator(op: ast.AST) -> str:
    mapping = {
        ast.Not: "not ",
        ast.UAdd: "+",
        ast.USub: "-",
        ast.Invert: "~",
    }
    for cls, symbol in mapping.items():
        if isinstance(op, cls):
            return symbol
    return ""


MAX_MD_HEADINGS = 20
MAX_MD_HEADING_CHARS = 100
MAX_JSON_KEYS = 30
MAX_JSON_BYTES = 100 * 1024
MAX_NON_CODE_KEYS = 30

MAX_REPLACEMENT_CHARS_NON_CODE = {
    "outline": 800,
    "key_tree": 800,
    "section_list": 600,
}


def _summarize_non_code_source(
    source: str,
    *,
    file_path: str,
    suffix: str,
    offset: int = 0,
    limit: int = 0,
    file_tokens_est: Optional[int] = None,
    file_size_bytes: Optional[int] = None,
) -> StructureMapResult:
    if file_size_bytes is None:
        file_size_bytes = len(source.encode("utf-8", errors="ignore"))
    if file_tokens_est is None:
        file_tokens_est = estimate_tokens(source)

    language = LANGUAGE_LABELS.get(suffix, "unknown")
    line_count = source.count("\n") + (1 if source else 0)

    if offset != 0 or limit != 0:
        return _build_fallback_result(
            file_path=file_path, language=language, source=source,
            reason="partial_range_not_supported", confidence=0.12,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    if not source.strip():
        return _build_fallback_result(
            file_path=file_path, language=language, source=source,
            reason="empty_file", confidence=0.05,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    if suffix == ".md":
        return _summarize_markdown(source, file_path=file_path,
                                   line_count=line_count,
                                   file_tokens_est=file_tokens_est,
                                   file_size_bytes=file_size_bytes)
    if suffix == ".json":
        return _summarize_json(source, file_path=file_path,
                               line_count=line_count,
                               file_tokens_est=file_tokens_est,
                               file_size_bytes=file_size_bytes)
    if suffix in (".yaml", ".yml"):
        return _summarize_yaml(source, file_path=file_path,
                               line_count=line_count,
                               file_tokens_est=file_tokens_est,
                               file_size_bytes=file_size_bytes)
    if suffix == ".toml":
        return _summarize_toml(source, file_path=file_path,
                               line_count=line_count,
                               file_tokens_est=file_tokens_est,
                               file_size_bytes=file_size_bytes)

    return _build_fallback_result(
        file_path=file_path, language=language, source=source,
        reason="unsupported_language", confidence=0.10,
        parse_ok=False, generated_like=False,
        file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
    )


def _summarize_markdown(
    source: str, *, file_path: str, line_count: int,
    file_tokens_est: Optional[int], file_size_bytes: Optional[int],
) -> StructureMapResult:
    lines = source.splitlines()
    headings: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            title = stripped.lstrip("#").strip()
            if 1 <= level <= 4 and title:
                indent = "  " * (level - 1)
                headings.append(f"{indent}{title[:MAX_MD_HEADING_CHARS]}")
        if len(headings) >= MAX_MD_HEADINGS:
            break

    if not headings:
        return _build_fallback_result(
            file_path=file_path, language="markdown", source=source,
            reason="no_headings", confidence=0.15,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    name = Path(file_path).name
    rendered = f"Markdown outline for {name} ({line_count} lines):\n"
    rendered += "\n".join(headings)
    if len(headings) == MAX_MD_HEADINGS:
        rendered += f"\n... (truncated at {MAX_MD_HEADINGS} headings)"

    cap = MAX_REPLACEMENT_CHARS_NON_CODE["outline"]
    if len(rendered) > cap:
        rendered = rendered[:cap - 3] + "..."

    fp = _fingerprint(path=file_path, replacement_type="outline",
                       rendered=rendered, line_count=line_count,
                       file_size_bytes=file_size_bytes)
    return StructureMapResult(
        file_path=file_path, language="markdown",
        replacement_type="outline", replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=0.90, fingerprint=fp, eligible=True,
        reason="ok", generated_like=False, parse_ok=True,
        line_count=line_count, file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def _json_type_hint(val: object) -> str:
    if isinstance(val, dict):
        return f"object({len(val)} keys)"
    if isinstance(val, list):
        return f"array({len(val)})"
    if isinstance(val, str):
        return f"string({len(val)}ch)" if len(val) > 40 else f'"{val}"'
    if isinstance(val, bool):
        return str(val).lower()
    if isinstance(val, (int, float)):
        return str(val)
    if val is None:
        return "null"
    return type(val).__name__


def _extract_json_keys(
    data: object, depth: int, max_depth: int, max_keys: int,
) -> list[str]:
    result: list[str] = []
    if depth > max_depth or len(result) >= max_keys:
        return result
    if isinstance(data, dict):
        for key in list(data.keys())[:max_keys - len(result)]:
            val = data[key]
            indent = "  " * depth
            hint = _json_type_hint(val)
            result.append(f"{indent}{key}: {hint}")
            if isinstance(val, dict) and depth < max_depth:
                result.extend(_extract_json_keys(val, depth + 1, max_depth, max_keys - len(result)))
            if len(result) >= max_keys:
                break
    elif isinstance(data, list) and data:
        result.append(f"{'  ' * depth}[{len(data)} items, first: {_json_type_hint(data[0])}]")
    return result[:max_keys]


def _summarize_json(
    source: str, *, file_path: str, line_count: int,
    file_tokens_est: Optional[int], file_size_bytes: Optional[int],
) -> StructureMapResult:
    raw_bytes = len(source.encode("utf-8", errors="replace"))
    if raw_bytes > MAX_JSON_BYTES:
        return _build_fallback_result(
            file_path=file_path, language="json", source=source,
            reason="too_large_to_parse", confidence=0.10,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )
    try:
        import json as _json
        data = _json.loads(source)
    except (ValueError, RecursionError):
        return _build_fallback_result(
            file_path=file_path, language="json", source=source,
            reason="parse_error", confidence=0.10,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    keys = _extract_json_keys(data, depth=0, max_depth=2, max_keys=MAX_JSON_KEYS)
    if not keys:
        return _build_fallback_result(
            file_path=file_path, language="json", source=source,
            reason="no_keys", confidence=0.15,
            parse_ok=True, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    name = Path(file_path).name
    rendered = f"JSON structure for {name}:\n" + "\n".join(keys)
    cap = MAX_REPLACEMENT_CHARS_NON_CODE["key_tree"]
    if len(rendered) > cap:
        rendered = rendered[:cap - 3] + "..."

    fp = _fingerprint(path=file_path, replacement_type="key_tree",
                       rendered=rendered, line_count=line_count,
                       file_size_bytes=file_size_bytes)
    return StructureMapResult(
        file_path=file_path, language="json",
        replacement_type="key_tree", replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=0.92, fingerprint=fp, eligible=True,
        reason="ok", generated_like=False, parse_ok=True,
        line_count=line_count, file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def _summarize_yaml(
    source: str, *, file_path: str, line_count: int,
    file_tokens_est: Optional[int], file_size_bytes: Optional[int],
) -> StructureMapResult:
    lines = source.splitlines()
    indent_unit = 2
    for ln in lines:
        if ln and ln[0] == " ":
            spaces = len(ln) - len(ln.lstrip())
            if spaces > 0:
                indent_unit = spaces
                break

    keys: list[str] = []
    for line in lines:
        stripped = line.rstrip()
        if not stripped or stripped.lstrip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        depth = indent // max(indent_unit, 1)
        if depth <= 2 and ":" in stripped:
            key_part = stripped.split(":")[0].strip().lstrip("- ")
            if key_part and not key_part.startswith("#"):
                keys.append(f"{'  ' * depth}{key_part}")
        if len(keys) >= MAX_NON_CODE_KEYS:
            break

    if not keys:
        return _build_fallback_result(
            file_path=file_path, language="yaml", source=source,
            reason="no_keys", confidence=0.15,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    name = Path(file_path).name
    rendered = f"YAML key tree for {name} ({line_count} lines):\n" + "\n".join(keys)
    cap = MAX_REPLACEMENT_CHARS_NON_CODE["key_tree"]
    if len(rendered) > cap:
        rendered = rendered[:cap - 3] + "..."

    fp = _fingerprint(path=file_path, replacement_type="key_tree",
                       rendered=rendered, line_count=line_count,
                       file_size_bytes=file_size_bytes)
    return StructureMapResult(
        file_path=file_path, language="yaml",
        replacement_type="key_tree", replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=0.85, fingerprint=fp, eligible=True,
        reason="ok", generated_like=False, parse_ok=True,
        line_count=line_count, file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def _summarize_toml(
    source: str, *, file_path: str, line_count: int,
    file_tokens_est: Optional[int], file_size_bytes: Optional[int],
) -> StructureMapResult:
    sections: list[str] = []
    top_keys: list[str] = []
    for line in source.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            sections.append(stripped)
        elif "=" in stripped and not stripped.startswith("#"):
            key = stripped.split("=")[0].strip()
            if key and len(top_keys) < 15:
                top_keys.append(key)

    if not sections and not top_keys:
        return _build_fallback_result(
            file_path=file_path, language="toml", source=source,
            reason="no_structure", confidence=0.15,
            parse_ok=False, generated_like=False,
            file_tokens_est=file_tokens_est, file_size_bytes=file_size_bytes,
        )

    name = Path(file_path).name
    parts = [f"TOML structure for {name} ({line_count} lines):"]
    if sections:
        parts.append("Sections:")
        parts.extend(f"  {s}" for s in sections[:15])
        if len(sections) > 15:
            parts.append(f"  ... ({len(sections) - 15} more)")
    if top_keys:
        parts.append("Top-level keys:")
        parts.extend(f"  {k}" for k in top_keys)

    rendered = "\n".join(parts)
    cap = MAX_REPLACEMENT_CHARS_NON_CODE["section_list"]
    if len(rendered) > cap:
        rendered = rendered[:cap - 3] + "..."

    fp = _fingerprint(path=file_path, replacement_type="section_list",
                       rendered=rendered, line_count=line_count,
                       file_size_bytes=file_size_bytes)
    return StructureMapResult(
        file_path=file_path, language="toml",
        replacement_type="section_list", replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=0.88, fingerprint=fp, eligible=True,
        reason="ok", generated_like=False, parse_ok=True,
        line_count=line_count, file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def _build_fallback_result(
    *,
    file_path: str,
    language: str,
    source: str,
    reason: str,
    confidence: float,
    parse_ok: bool,
    generated_like: bool,
    file_tokens_est: Optional[int],
    file_size_bytes: Optional[int],
) -> StructureMapResult:
    line_count = source.count("\n") + (1 if source else 0)
    rendered = _render_digest(source=source, file_path=file_path, line_count=line_count)
    fingerprint = _fingerprint(
        path=file_path,
        replacement_type="digest",
        rendered=rendered,
        line_count=line_count,
        file_size_bytes=file_size_bytes,
    )
    return StructureMapResult(
        file_path=file_path,
        language=language,
        replacement_type="digest",
        replacement_text=rendered,
        replacement_tokens_est=estimate_tokens(rendered),
        confidence=max(0.05, min(1.0, confidence)),
        fingerprint=fingerprint,
        eligible=False,
        reason=reason,
        generated_like=generated_like,
        parse_ok=parse_ok,
        line_count=line_count,
        file_tokens_est=file_tokens_est,
        file_size_bytes=file_size_bytes,
    )


def _render_digest(*, source: str, file_path: str, line_count: int) -> str:
    lines = source.splitlines()
    if not lines:
        return f"digest fallback for {Path(file_path).name or file_path}\nlines: 0"

    non_empty = [line.rstrip() for line in lines if line.strip()]
    head = non_empty[:MAX_DIGEST_HEAD_LINES]
    tail = non_empty[-MAX_DIGEST_TAIL_LINES:] if len(non_empty) > MAX_DIGEST_HEAD_LINES + MAX_DIGEST_TAIL_LINES else []

    parts = [f"digest fallback for {Path(file_path).name or file_path}", f"lines: {line_count}"]
    if head:
        parts.append("head:")
        parts.extend(f"  - {line[:160]}" for line in head)
    if tail:
        parts.append("tail:")
        parts.extend(f"  - {line[:160]}" for line in tail)

    rendered = "\n".join(parts)
    cap = MAX_REPLACEMENT_CHARS["digest"]
    if len(rendered) <= cap:
        return rendered
    return rendered[: max(0, cap - 1)] + "…"


def _choose_replacement_type(
    *,
    file_tokens_est: int,
    line_count: int,
    class_count: int,
    function_count: int,
    assignment_count: int,
    method_count: int,
) -> str:
    total_symbols = class_count + function_count + assignment_count
    has_classes = class_count > 0
    has_methods = method_count > 0
    large_file = file_tokens_est >= 3500 or line_count >= 900 or total_symbols >= 18
    moderate_file = file_tokens_est >= 1500 or line_count >= 220 or total_symbols >= 8

    if has_classes and has_methods and moderate_file:
        return "skeleton"
    if large_file:
        return "signatures"
    if total_symbols <= 6 and line_count <= 180:
        return "top_level"
    if has_classes and moderate_file:
        return "skeleton"
    if total_symbols <= 12:
        return "top_level"
    return "signatures"


def _shrink_or_fallback(
    *,
    path: str,
    line_count: int,
    module_docstring: Optional[str],
    imports: Sequence[str],
    classes: Sequence[_ClassSummary],
    functions: Sequence[_FunctionSummary],
    assignments: Sequence[str],
    preferred: str,
) -> Tuple[str, str]:
    order = {
        "skeleton": ["skeleton", "top_level", "signatures", "digest"],
        "top_level": ["top_level", "signatures", "digest"],
        "signatures": ["signatures", "top_level", "digest"],
        "digest": ["digest"],
    }.get(preferred, ["digest"])

    for replacement_type in order:
        rendered = _render_candidate(
            replacement_type,
            path=path,
            line_count=line_count,
            module_docstring=module_docstring,
            imports=imports,
            classes=classes,
            functions=functions,
            assignments=assignments,
        )
        if len(rendered) <= MAX_REPLACEMENT_CHARS[replacement_type]:
            return rendered, replacement_type

    rendered = _render_digest_lines(path=path, line_count=line_count)
    return "\n".join(rendered), "digest"


def _score_confidence(
    *,
    replacement_type: str,
    line_count: int,
    file_tokens_est: int,
    class_count: int,
    function_count: int,
    method_count: int,
    rendered_len: int,
    parse_ok: bool,
    generated_like: bool,
) -> float:
    base = {
        "skeleton": 0.90,
        "top_level": 0.94,
        "signatures": 0.86,
        "digest": 0.28,
    }.get(replacement_type, 0.35)

    if parse_ok:
        base += 0.02
    if generated_like:
        base -= 0.20
    if file_tokens_est >= 4000:
        base -= 0.05
    if line_count >= 1200:
        base -= 0.05
    if class_count >= 3:
        base -= 0.03
    if method_count >= 8:
        base -= 0.04
    if function_count >= 12:
        base -= 0.03
    if rendered_len >= MAX_REPLACEMENT_CHARS.get(replacement_type, rendered_len):
        base -= 0.04

    return round(max(0.05, min(0.98, base)), 3)


def _fingerprint(
    *,
    path: str,
    replacement_type: str,
    rendered: str,
    line_count: int,
    file_size_bytes: Optional[int],
) -> str:
    payload = "\n".join(
        [
            "structure-map-v1",
            replacement_type,
            path,
            str(line_count),
            str(file_size_bytes or 0),
            rendered,
        ]
    )
    return hashlib.sha256(payload.encode("utf-8", errors="ignore")).hexdigest()


def _short_docstring(docstring: Optional[str]) -> str:
    if not docstring:
        return ""
    compact = " ".join(docstring.strip().split())
    if len(compact) <= MAX_DOCSTRING_CHARS:
        return compact
    return compact[: MAX_DOCSTRING_CHARS - 1] + "…"


def _shorten_list(items: Sequence, limit: int) -> List:
    if len(items) <= limit:
        return list(items)
    return list(items[:limit])


def _flatten_targets(node: ast.AST) -> List[str]:
    names: List[str] = []
    if isinstance(node, ast.Name):
        names.append(node.id)
    elif isinstance(node, (ast.Tuple, ast.List)):
        for child in node.elts:
            names.extend(_flatten_targets(child))
    elif isinstance(node, ast.Attribute):
        names.append(_render_expr(node))
    return names


def _is_public_symbol(name: str) -> bool:
    if name == "__all__":
        return True
    return not name.startswith("_")


__all__ = [
    "StructureMapResult",
    "detect_structure_language",
    "estimate_tokens",
    "is_js_ts_file",
    "is_python_file",
    "is_structure_supported_file",
    "looks_generated_js_ts",
    "looks_generated_python",
    "summarize_code_file",
    "summarize_code_source",
    "summarize_js_ts_source",
    "summarize_python_file",
    "summarize_python_source",
]
MAX_JS_TS_IMPORTS = 3
MAX_JS_TS_SIGNATURE_ITEMS = 6
MAX_JS_TS_TOP_LEVEL_SYMBOLS = 8
MAX_JS_TS_SKELETON_FUNCTIONS = 5
MAX_JS_TS_SKELETON_SYMBOLS = 4
