"""Cache instability detector: flags CLAUDE.md patterns that break Anthropic prompt cache prefix stability."""

import json
import os
import re
import tempfile
import time
from pathlib import Path

_TIMESTAMP_PATTERNS = [
    re.compile(r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}"),  # ISO datetime
    re.compile(r"(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),?\s+\w+\s+\d{1,2}"),  # Day, Month DD
    re.compile(r"Updated:\s*\d{4}-\d{2}-\d{2}"),  # Updated: YYYY-MM-DD
    re.compile(r"Last (?:updated|modified|synced):\s*\d"),  # Last updated: ...
    re.compile(r"^(?:>?\s*)?As of \d{4}-\d{2}"),  # As of 2026-04 (month-level = volatile, year-level = stable)
]

_DYNAMIC_SECTION_MARKERS = [
    "TOKEN_OPTIMIZER:MODEL_ROUTING",
    "AUTO-GENERATED",
    "DO NOT EDIT",
    "Generated by",
    "Synced from",
]

_IMPORT_RE = re.compile(r"@import\s+[\"']([^\"']+)[\"']")

# Volatile token indicators for @import paths in CLAUDE.md. Used ONLY by Signal
# 3 (the @import path scan), NOT by the MCP scan: MCP env/args/url VALUES never
# reach the model-facing prompt (only tool schemas do), so scanning them for
# these substrings produced pervasive false positives (any --log-level, a
# /status URL, a current-site path tripped it). The MCP signal now targets the
# server SET instead; see _scan_mcp_servers.
_VOLATILE_TOKENS = ("status", "log", "daily", "current", "temp", "cache")

# Module-level caches keyed by resolved cwd so the 10-session loop in
# run_all_detectors reads each surface file at most once per measure run.
_MCP_SCAN_CACHE: dict = {}
_PROCESS_SCAN_CACHE: dict = {}

# Bound on the number of process-library prefix files scanned, to keep the
# detector cheap even in repos with very large process trees.
_PROCESS_FILE_CAP = 40

# Cap on a single config/prefix file read, so a huge ~/.claude.json or a
# symlinked /dev/zero cannot hang or OOM a measure run. 1 MiB is far above any
# legitimate .mcp.json/.claude.json or process prefix file.
_READ_CAP_BYTES = 1_000_000

# State filename for the MCP server-set diff (Signal 4). Records the set of MCP
# server names per resolved cwd so a later run can detect add/remove -- the
# config-detectable proxy for tool-schema churn in the cached prefix.
_MCP_STATE_FILENAME = "cache_instability_mcp_state.json"


def _has_timestamp(text):
    """Return True if *text* matches any timestamp pattern."""
    return any(pat.search(text) for pat in _TIMESTAMP_PATTERNS)


def _safe_read_text(path):
    """Read up to ``_READ_CAP_BYTES`` from *path* without following symlinks.

    Returns the text (errors replaced) or ``None`` when the file is absent, a
    symlink, too large, or unreadable. Symlink rejection matters: a symlink in
    .claude/processes or a project .mcp.json must not be followed into
    /dev/zero or an attacker-chosen huge file. The cap matters for
    ~/.claude.json, which accumulates per-project history and can run to many
    MB. Fail-open: callers treat None as "no signal".
    """
    try:
        if not path.exists() or path.is_symlink():
            return None
        if path.stat().st_size > _READ_CAP_BYTES:
            return None
        return path.read_text(encoding="utf-8", errors="replace")
    except (PermissionError, OSError, ValueError):
        return None


def _state_dir():
    """Resolve a writable state dir for the detector, mirroring
    plugin_env.resolve_snapshot_dir() without importing it (detectors stay
    standalone to avoid a circular import). TOKEN_OPTIMIZER_SNAPSHOT_DIR wins
    (tests/sandbox); else CLAUDE_PLUGIN_DATA/data; else
    ~/.claude/token-optimizer/data. Returns None only if HOME itself is
    unresolvable, in which case the snapshot diff is skipped (no finding, no
    crash).
    """
    override = os.environ.get("TOKEN_OPTIMIZER_SNAPSHOT_DIR", "").strip()
    if override:
        return Path(override).expanduser()
    plugin_data = os.environ.get("CLAUDE_PLUGIN_DATA", "").strip()
    if plugin_data:
        return Path(plugin_data).expanduser() / "data"
    try:
        return Path.home() / ".claude" / "token-optimizer" / "data"
    except (RuntimeError, OSError):
        return None


def _scan_prefix_lines(lines, surface_label, cutoff_ratio=0.6):
    """Run the timestamp-pattern scan and the auto-gen-marker scan over *lines*.

    Returns the same finding dicts the CLAUDE.md path produces today, with the
    surface label parameterised so the helper can be reused for other
    cache-prefix-resident surfaces. When *surface_label* is ``"CLAUDE.md"`` the
    output is byte-identical to the pre-refactor CLAUDE.md signals.
    """
    if not lines:
        return []

    findings = []
    prefix_cutoff = int(len(lines) * cutoff_ratio)

    # Signal 1: Timestamps or dates in the first 60% of the surface
    early_timestamps = []
    for i, line in enumerate(lines[:prefix_cutoff]):
        for pat in _TIMESTAMP_PATTERNS:
            if pat.search(line):
                early_timestamps.append((i + 1, line.strip()[:80]))
                break

    if early_timestamps:
        # Tokens wasted = everything after the first timestamp that could be cached
        first_ts_line = early_timestamps[0][0]
        chars_after = sum(len(lines[i]) for i in range(first_ts_line, len(lines)))
        wasted_tokens = chars_after // 4
        if wasted_tokens > 500:
            evidence_lines = "; ".join(f"L{ln}" for ln, _ in early_timestamps[:3])
            findings.append({
                "name": "cache_instability",
                "confidence": 0.75,
                "evidence": (
                    f"Timestamps in {surface_label} prefix ({evidence_lines}) invalidate prompt cache "
                    f"for ~{wasted_tokens:,} tokens of stable content below them"
                ),
                "savings_tokens": wasted_tokens,
                "suggestion": (
                    f"Move timestamped content to the bottom of {surface_label}. "
                    f"Anthropic's prompt cache is prefix-based: everything before the first "
                    f"changing line gets cached. ~{wasted_tokens:,} tokens of stable rules "
                    f"could get cache hits (90% cost reduction) if timestamps move to the end."
                ),
                "occurrence_count": len(early_timestamps),
            })

    # Signal 2: Auto-generated sections in the first 60%
    dynamic_sections = []
    for i, line in enumerate(lines[:prefix_cutoff]):
        for marker in _DYNAMIC_SECTION_MARKERS:
            if marker in line:
                dynamic_sections.append((i + 1, marker))
                break

    if dynamic_sections:
        first_dynamic = dynamic_sections[0][0]
        chars_after = sum(len(lines[i]) for i in range(first_dynamic, len(lines)))
        wasted_tokens = chars_after // 4
        if wasted_tokens > 500:
            markers_found = ", ".join(m for _, m in dynamic_sections[:3])
            findings.append({
                "name": "cache_instability",
                "confidence": 0.7,
                "evidence": (
                    f"Auto-generated sections in {surface_label} prefix ({markers_found} at "
                    f"L{first_dynamic}) change between sessions, breaking cache"
                ),
                "savings_tokens": wasted_tokens,
                "suggestion": (
                    f"Move auto-generated sections to the end of {surface_label}. "
                    "Content that changes per-session should be after stable content "
                    "to preserve prompt cache hits on the prefix."
                ),
                "occurrence_count": len(dynamic_sections),
            })

    return findings


def _mcp_candidate_files(cwd):
    """Return the ordered list of MCP config files to inspect for *cwd*.

    Project-local files first, then the home fallback. Order matters: the
    project-local ``.claude.json`` overrides the home one for the server-set
    scan.
    """
    cwd_path = Path(cwd)
    return [
        cwd_path / ".mcp.json",
        cwd_path / ".claude.json",
        Path.home() / ".claude.json",
    ]


def _read_mcp_server_set(cwd):
    """Return the set of MCP server names configured for *cwd*.

    Union of the ``mcpServers`` keys across the candidate config files.
    ``env``/``args``/``url``/``command`` VALUES are deliberately NOT inspected:
    they never reach the model-facing prompt (the host loads them to spawn
    servers; the model receives tool SCHEMAS, not the env values), so their
    churn does not invalidate the prompt cache. The server SET is the
    config-detectable proxy for tool-schema churn: adding or removing a server
    changes the set of tool schemas injected into the cached prefix.
    """
    servers = set()
    for path in _mcp_candidate_files(cwd):
        text = _safe_read_text(path)
        if text is None:
            continue
        try:
            data = json.loads(text)
        except (json.JSONDecodeError, ValueError):
            continue
        if not isinstance(data, dict):
            continue
        s = data.get("mcpServers")
        if not isinstance(s, dict):
            continue
        for name, cfg in s.items():
            if isinstance(cfg, dict):
                servers.add(str(name))
    return servers


def _load_mcp_state(state_path):
    """Read the persisted server-set state, or {} on any error/missing file."""
    if state_path is None:
        return {}
    text = _safe_read_text(state_path)
    if text is None:
        return {}
    try:
        data = json.loads(text)
    except (json.JSONDecodeError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _save_mcp_state(state_path, state):
    """Atomically persist the server-set state. Fail-open on any I/O error."""
    if state_path is None:
        return
    try:
        state_path.parent.mkdir(parents=True, exist_ok=True)
        # Unique temp name (not a fixed ".tmp" sibling): two concurrent measure
        # runs in different cwds would otherwise write the SAME ".tmp" and clobber
        # each other, so one os.replace promotes the wrong content and the other
        # raises FileNotFoundError. mkstemp gives each writer its own temp.
        fd, tmp = tempfile.mkstemp(dir=str(state_path.parent), prefix=state_path.name + ".", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(json.dumps(state))
            os.replace(tmp, state_path)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
    except (PermissionError, OSError, ValueError):
        pass


def _scan_mcp_servers(cwd):
    """Signal 4: detect MCP server add/remove between measure runs.

    The cached prompt prefix includes the tool-schema block the host builds from
    the configured MCP servers. Adding or removing a server changes that block
    and invalidates the cache for everything after it -- the same effect a
    CLAUDE.md edit has. The server SET (the ``mcpServers`` keys in .mcp.json /
    .claude.json) is the config-detectable proxy for that churn.

    What this does NOT do, and why: it does not scan ``env``/``args``/``url``
    VALUES. Those never reach the model-facing prompt (only tool schemas do), so
    their churn does not break the prefix cache; scanning them for volatile
    substrings was the old behaviour and produced pervasive false positives
    (any ``--log-level``, a ``/status`` URL, a ``current-site`` path tripped
    it). It also does not detect per-tool description/count churn, because that
    is not visible in config files -- it requires runtime tool-list capture,
    which is out of scope for a config-file detector.

    State: one entry per resolved cwd in ``_MCP_STATE_FILENAME`` under the
    snapshot dir. The first run for a cwd records a baseline and fires nothing
    (there is no prior set to diff against); subsequent runs fire when the set
    changes and update the baseline. Fail-open on any I/O error.
    """
    key = str(Path(cwd).resolve())
    if key in _MCP_SCAN_CACHE:
        return _MCP_SCAN_CACHE[key]

    findings = []
    current = _read_mcp_server_set(cwd)

    state_dir = _state_dir()
    state_path = (state_dir / _MCP_STATE_FILENAME) if state_dir is not None else None
    state = _load_mcp_state(state_path)
    prev_entry = state.get(key)
    prev_servers = None
    if isinstance(prev_entry, dict):
        ps = prev_entry.get("servers")
        if isinstance(ps, list):
            prev_servers = set(ps)

    # First run for this cwd: record baseline, no churn to report yet.
    if prev_servers is None:
        state[key] = {"servers": sorted(current), "ts": time.time()}
        _save_mcp_state(state_path, state)
        _MCP_SCAN_CACHE[key] = findings
        return findings

    added = current - prev_servers
    removed = prev_servers - current

    # Persist the new baseline regardless of whether we fire.
    state[key] = {"servers": sorted(current), "ts": time.time()}
    _save_mcp_state(state_path, state)

    if added or removed:
        parts = []
        if added:
            parts.append("+ " + ", ".join(sorted(added)[:5]))
        if removed:
            parts.append("- " + ", ".join(sorted(removed)[:5]))
        findings.append({
            "name": "cache_instability",
            "confidence": 0.7,
            "evidence": (
                f"MCP server set changed since last measure ({'; '.join(parts)}): "
                f"adding/removing a server changes the tool schemas in the cached "
                f"prompt prefix, invalidating the cache for everything after them"
            ),
            "savings_tokens": 1500,
            "suggestion": (
                "MCP server add/remove changes the tool-schema block in the cached "
                "prefix, so each rotation costs one uncached turn. Keep the server "
                "set stable across sessions. (Per-tool description churn is not "
                "detectable from config files alone and is not flagged here.)"
            ),
            "occurrence_count": len(added) + len(removed),
        })

    _MCP_SCAN_CACHE[key] = findings
    return findings


def _process_prefix_dirs(cwd):
    """Return the ordered list of process-library prefix directories to scan."""
    cwd_path = Path(cwd)
    home = Path.home()
    return [
        cwd_path / ".a5c" / "processes",
        cwd_path / ".claude" / "processes",
        home / ".a5c" / "processes",
        home / ".claude" / "processes",
    ]


def _scan_process_prefixes(cwd):
    """Signal 5: scan process-library prompt prefix files for cache-prefix churn.

    ``.a5c/processes`` and ``.claude/processes`` hold prompt prefix files that
    are loaded into the cached prefix; timestamps or auto-gen markers in their
    first 60% break the cache. Bounded by ``_PROCESS_FILE_CAP`` and
    ``_READ_CAP_BYTES``; symlinks are not followed (a symlinked entry must not
    pull in an arbitrary huge file). Fail-open.
    """
    key = str(Path(cwd).resolve())
    if key in _PROCESS_SCAN_CACHE:
        return _PROCESS_SCAN_CACHE[key]

    findings = []
    unstable_files = []
    try:
        scanned = 0
        for directory in _process_prefix_dirs(cwd):
            if not directory.exists() or not directory.is_dir() or directory.is_symlink():
                continue
            for path in sorted(directory.iterdir()):
                if scanned >= _PROCESS_FILE_CAP:
                    break
                if not path.is_file() or path.is_symlink() or path.suffix not in (".md", ".txt"):
                    continue
                scanned += 1
                text = _safe_read_text(path)
                if text is None or len(text) < 50:
                    continue
                lines = text.splitlines()
                prefix_cutoff = int(len(lines) * 0.6) or 1
                for line in lines[:prefix_cutoff]:
                    if _has_timestamp(line):
                        unstable_files.append(path.name)
                        break
                    if any(marker in line for marker in _DYNAMIC_SECTION_MARKERS):
                        unstable_files.append(path.name)
                        break
            if scanned >= _PROCESS_FILE_CAP:
                break
    except (PermissionError, OSError):
        pass

    if unstable_files:
        names = ", ".join(unstable_files[:5])
        findings.append({
            "name": "cache_instability",
            "confidence": 0.6,
            "evidence": (
                f"Process-library prompt prefix files contain timestamps or auto-gen "
                f"markers in their first 60% ({names}), breaking the cached prefix"
            ),
            "savings_tokens": 1500,
            "suggestion": (
                "Move timestamped or auto-generated content in .a5c/processes and "
                ".claude/processes prefix files to the end of each file, or strip the "
                "volatile header. These files load into the cached prompt prefix."
            ),
            "occurrence_count": len(unstable_files),
        })

    _PROCESS_SCAN_CACHE[key] = findings
    return findings


def detect_cache_instability(session_data):
    """Detect CLAUDE.md patterns that break Anthropic's prefix-based prompt cache.

    Anthropic caches a byte-identical prefix. Content that changes between sessions
    (timestamps, auto-generated sections, volatile imports) invalidates the cache
    for everything after it. Moving volatile content to the end preserves cache hits
    on the stable prefix.

    Surfaces scanned (all additive to the original CLAUDE.md signals):
      1-3. CLAUDE.md prefix: timestamps, auto-gen markers, volatile @imports.
      4.   MCP server add/remove in .mcp.json / .claude.json (the server set is
           the config-detectable proxy for tool-schema churn in the cached
           prefix; env/args/url values are NOT scanned -- they never reach the
           model-facing prompt).
      5.   Process-library prompt prefix files in .a5c/processes, .claude/processes.
    """
    claude_md = session_data.get("claude_md_content", "")
    # New surfaces must still run when CLAUDE.md is absent/small. With an empty
    # `lines` list every original prefix loop is a no-op, so the 3 original
    # signals behave exactly as before when CLAUDE.md is missing.
    lines = claude_md.splitlines() if (claude_md and len(claude_md) >= 200) else []

    findings = []

    # Signals 1 & 2: timestamps and auto-gen markers in the CLAUDE.md prefix.
    # _scan_prefix_lines with surface_label="CLAUDE.md" is byte-identical to the
    # pre-refactor CLAUDE.md path.
    findings.extend(_scan_prefix_lines(lines, "CLAUDE.md"))

    # Signal 3: @import of volatile files in the first 60%
    if lines:
        prefix_cutoff = int(len(lines) * 0.6)
        volatile_imports = []
        for i, line in enumerate(lines[:prefix_cutoff]):
            match = _IMPORT_RE.search(line)
            if match:
                path = match.group(1)
                if any(v in path.lower() for v in _VOLATILE_TOKENS):
                    volatile_imports.append((i + 1, path))

        if volatile_imports:
            findings.append({
                "name": "cache_instability",
                "confidence": 0.6,
                "evidence": (
                    "@import of volatile files in CLAUDE.md prefix: "
                    + ", ".join(p for _, p in volatile_imports[:3])
                ),
                "savings_tokens": 2000,
                "suggestion": (
                    "Move @import of volatile files to the end of CLAUDE.md, or use "
                    "path-scoped rules files instead (which only load when relevant)."
                ),
                "occurrence_count": len(volatile_imports),
            })

    # Signal 4: MCP server add/remove (cached-prefix tool-schema churn).
    findings.extend(_scan_mcp_servers(Path.cwd()))

    # Signal 5: process-library prompt prefix files (cached-prefix-resident).
    findings.extend(_scan_process_prefixes(Path.cwd()))

    return findings
