"""Cache instability detector: flags CLAUDE.md patterns that break Anthropic prompt cache prefix stability."""

import re

_TIMESTAMP_PATTERNS = [
    re.compile(r"\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}"),  # ISO datetime
    re.compile(r"(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun),?\s+\w+\s+\d{1,2}"),  # Day, Month DD
    re.compile(r"Updated:\s*\d{4}-\d{2}-\d{2}"),  # Updated: YYYY-MM-DD
    re.compile(r"Last (?:updated|modified|synced):\s*\d"),  # Last updated: ...
    re.compile(r"^(?:>?\s*)?As of \d{4}-\d{2}"),  # As of 2026-04 (month-level = volatile, year-level = stable)
]

_DYNAMIC_SECTION_MARKERS = [
    "TOKEN_OPTIMIZER:MODEL_ROUTING",
    "AUTO-GENERATED",
    "DO NOT EDIT",
    "Generated by",
    "Synced from",
]

_IMPORT_RE = re.compile(r"@import\s+[\"']([^\"']+)[\"']")


def detect_cache_instability(session_data):
    """Detect CLAUDE.md patterns that break Anthropic's prefix-based prompt cache.

    Anthropic caches a byte-identical prefix. Content that changes between sessions
    (timestamps, auto-generated sections, volatile imports) invalidates the cache
    for everything after it. Moving volatile content to the end preserves cache hits
    on the stable prefix.
    """
    claude_md = session_data.get("claude_md_content", "")
    if not claude_md or len(claude_md) < 200:
        return []

    findings = []
    lines = claude_md.splitlines()

    # Signal 1: Timestamps or dates in the first 60% of CLAUDE.md
    prefix_cutoff = int(len(lines) * 0.6)
    early_timestamps = []
    for i, line in enumerate(lines[:prefix_cutoff]):
        for pat in _TIMESTAMP_PATTERNS:
            if pat.search(line):
                early_timestamps.append((i + 1, line.strip()[:80]))
                break

    if early_timestamps:
        # Tokens wasted = everything after the first timestamp that could be cached
        first_ts_line = early_timestamps[0][0]
        chars_after = sum(len(lines[i]) for i in range(first_ts_line, len(lines)))
        wasted_tokens = chars_after // 4
        if wasted_tokens > 500:
            evidence_lines = "; ".join(f"L{ln}" for ln, _ in early_timestamps[:3])
            findings.append({
                "name": "cache_instability",
                "confidence": 0.75,
                "evidence": (
                    f"Timestamps in CLAUDE.md prefix ({evidence_lines}) invalidate prompt cache "
                    f"for ~{wasted_tokens:,} tokens of stable content below them"
                ),
                "savings_tokens": wasted_tokens,
                "suggestion": (
                    f"Move timestamped content to the bottom of CLAUDE.md. "
                    f"Anthropic's prompt cache is prefix-based: everything before the first "
                    f"changing line gets cached. ~{wasted_tokens:,} tokens of stable rules "
                    f"could get cache hits (90% cost reduction) if timestamps move to the end."
                ),
                "occurrence_count": len(early_timestamps),
            })

    # Signal 2: Auto-generated sections in the first 60%
    dynamic_sections = []
    for i, line in enumerate(lines[:prefix_cutoff]):
        for marker in _DYNAMIC_SECTION_MARKERS:
            if marker in line:
                dynamic_sections.append((i + 1, marker))
                break

    if dynamic_sections:
        first_dynamic = dynamic_sections[0][0]
        chars_after = sum(len(lines[i]) for i in range(first_dynamic, len(lines)))
        wasted_tokens = chars_after // 4
        if wasted_tokens > 500:
            markers_found = ", ".join(m for _, m in dynamic_sections[:3])
            findings.append({
                "name": "cache_instability",
                "confidence": 0.7,
                "evidence": (
                    f"Auto-generated sections in CLAUDE.md prefix ({markers_found} at "
                    f"L{dynamic_sections[0][0]}) change between sessions, breaking cache"
                ),
                "savings_tokens": wasted_tokens,
                "suggestion": (
                    "Move auto-generated sections to the end of CLAUDE.md. "
                    "Content that changes per-session should be after stable content "
                    "to preserve prompt cache hits on the prefix."
                ),
                "occurrence_count": len(dynamic_sections),
            })

    # Signal 3: @import of volatile files in the first 60%
    volatile_imports = []
    for i, line in enumerate(lines[:prefix_cutoff]):
        match = _IMPORT_RE.search(line)
        if match:
            path = match.group(1)
            volatile_indicators = ["status", "log", "daily", "current", "temp", "cache"]
            if any(v in path.lower() for v in volatile_indicators):
                volatile_imports.append((i + 1, path))

    if volatile_imports:
        findings.append({
            "name": "cache_instability",
            "confidence": 0.6,
            "evidence": (
                "@import of volatile files in CLAUDE.md prefix: "
                + ", ".join(p for _, p in volatile_imports[:3])
            ),
            "savings_tokens": 2000,
            "suggestion": (
                "Move @import of volatile files to the end of CLAUDE.md, or use "
                "path-scoped rules files instead (which only load when relevant)."
            ),
            "occurrence_count": len(volatile_imports),
        })

    return findings
