#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

if [ "$(uname -s)" != "Darwin" ]; then
  echo "Error: Not on macOS."
  exit 1
fi

sudo defaults write \
  /Library/Preferences/SystemConfiguration/com.apple.DiskArbitration.diskarbitrationd.plist DADisableEjectNotification \
  -bool true &&
  sudo pkill diskarbitrationd
