#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

if [ "$(uname -s)" != "Darwin" ]; then
  echo "Error: Not on macOS."
  exit 1
fi

# Re-enable subpixel antialiasing, effective on next login (revert: set to true)
defaults write -g CGFontRenderingFontSmoothingDisabled -bool false

# https://osxdaily.com/2022/04/06/change-remove-font-smoothing-macos/
# 0: disabled, 1: light, 2: medium, 3: heavy, delete: reset
#defaults -currentHost write -g AppleFontSmoothing -int 0
#defaults -currentHost write -g AppleFontSmoothing -int 1
#defaults -currentHost write -g AppleFontSmoothing -int 2
#defaults -currentHost write -g AppleFontSmoothing -int 3
#defaults -currentHost delete -g AppleFontSmoothing
