#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

if [ "$(uname -s)" != "Darwin" ]; then
  echo "Error: Not on macOS."
  exit 1
fi

# Re-enable subpixel antialiasing, effective on next login (revert: set to true)
defaults write -g CGFontRenderingFontSmoothingDisabled -bool false

# 0: disable font smoothing, 1: enable font smoothing, delete: reset default
#defaults -currentHost write -g AppleFontSmoothing -int 0
#defaults -currentHost write -g AppleFontSmoothing -int 1
#defaults -currentHost delete -g AppleFontSmoothing
