# See: https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openai:gpt-4-turbo-preview   # LLM model
temperature: 1.0                    # GPT temperature, between 0 and 2
save: true                          # Whether to save the message
highlight: true                     # Set false to turn highlight
light_theme: false                  # Whether to use a light theme
wrap: auto                          # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                    # Whether wrap code block
auto_copy: false                    # Automatically copy the last output to the clipboard
keybindings: vi                     # REPL keybindings. (emacs, vi)
prelude: 'role:chat'                # Set a default role or session (role:<name>, session:<name>)

left_prompt: '{color.green}{?session {session}{?role /}}{role}{color.cyan}{?session )}{!session >}{color.reset} '
right_prompt: '{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{color.reset}'
