# See: https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openai:gpt-4o                # Default LLM
temperature: 0                      # GPT temperature, between 0 and 2
save: true                          # Whether to save the message
save_session: false                 # Whether to save the session, if null, asking
highlight: true                     # Set false to turn off highlight
light_theme: false                  # Whether to use a light theme
wrap: auto                          # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                    # Whether wrap code block
ctrlc_exit: true                    # Whether to exit REPL by pressing ^C twice
auto_copy: true                     # Automatically copy the last output to the clipboard
keybindings: vi                     # REPL keybindings. (emacs, vi)
prelude: 'role:chat'                # Set a default role or session (role:<name>, session:<name>)

# Compress session if tokens exceed this value (valid when >=1000)
#compress_threshold: 1000
# The prompt for summarizing session messages
#summarize_prompt: 'Summarize the discussion briefly in 200 words or less to use as a prompt for future context.'
# The prompt for the summary of the session
#summary_prompt: 'This is a summary of the chat history as a recap: '

left_prompt: '{color.green}{?session {session}{?role /}}{role}{color.cyan}{?session )}{!session >}{color.reset} '
right_prompt: '{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{color.reset}'

clients:
  - type: openai
  - type: claude
  - type: cohere
