#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Usage: $0 <target_dir>"
  exit 1
fi

target_path="$1"

# Check if the fabric directory exists
if [ -d "fabric" ]; then
  echo "Fabric repository already exists, pulling latest changes with rebase."
  pushd fabric >/dev/null || exit
  git pull --no-autostash --rebase origin main
  popd >/dev/null || exit
else
  echo "Cloning the latest commit of the fabric repository."
  git clone --depth 1 https://github.com/danielmiessler/fabric.git
fi

# Create target directory if it doesn't exist
mkdir -p "$target_path"

# Loop through all patterns and convert them
while IFS= read -r -d '' pattern_file; do
  # Extract pattern name from the path
  pattern_dir=$(dirname "$pattern_file")
  pattern_name=$(basename "$pattern_dir")

  # Create the output file path
  output_file="$target_path/${pattern_name}.md"

  # Copy the content of system.md to the output file
  cp "$pattern_file" "$output_file"

  # Remove trailing blank lines
  sed -i '' -e '$!N; /^\n*$/D' "$output_file"

  # Convert CRLF to LF
  sed -i '' 's/\r//g' "$output_file"

  # Trim trailing spaces
  while IFS= read -r line; do
    #shellcheck disable=SC2001
    echo "$line" | sed 's/[[:space:]]*$//'
  done <"$output_file" >"$output_file.tmp" && mv "$output_file.tmp" "$output_file"

  echo "Creating $output_file"
done < <(find fabric/patterns -name system.md -print0)

echo "Finished processing files."
