#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

### constants ##################################################################

this_path=$(cd "$(dirname "$0")" && pwd)

###  Write list of installed extensions to a file ##############################

if command -v cursor >/dev/null && [ "$DEFAULT_IDE" = "cursor" ]; then
  echo "Exporting Cursor extensions"
  bin_name="cursor"
elif command -v agy >/dev/null && [ "$DEFAULT_IDE" = "agy" ]; then
  echo "Exporting Antigravity extensions"
  bin_name="agy"
elif command -v code >/dev/null; then
  echo "Exporting VS Code extensions"
  bin_name="code"
else
  echo "Error: No VS Code like editor present."
  exit 1
fi

"$bin_name" --list-extensions >"$this_path/extensions.list"
