#!/bin/sh

# configent (https://github.com/raas-dev/configent)
# One command automated macOS/Linux laptop/VM/container bootstrapper.
#
# Copyright(C) 2016- Anssi Syrjäsalo (http://a.syrjasalo.com)
# Licensed under GNU Lesser General Public License v3 (LGPL-3.0).

this_path=$(cd "$(dirname "$0")" && pwd)

### Write installed extensions to a file #######################################

cursor_bin="/Applications/Cursor.app/Contents/Resources/app/bin/code"
if [ "$(uname -s)" = 'Darwin' ] && [ -e "$cursor_bin" ]; then
  code_bin="$cursor_bin"
else
  code_bin="code"
fi

"$code_bin" --list-extensions >"$this_path/extensions.list"
