lastChangelogVersion: 14.1.2
modelRoles:
  default: zai/glm-5.1
  smol: zai/glm-5-turbo
  slow: zai/glm-5.1
  vision: zai/glm-5v-turbo
  plan: zai/glm-5.1
  commit: zai/glm-5.1
renderMermaid:
  enabled: true
checkpoint:
  enabled: true
inspect_image:
  enabled: true
calc:
  enabled: true
commands:
  enableClaudeProject: false
  enableClaudeUser: false
providers:
  webSearch: exa
  image: auto
defaultThinkingLevel: medium
disabledProviders:
  - cursor
  - opencode
  - claude
theme:
  dark: ayu-dark
task:
  disabledAgents:
    - designer
  isolation:
    mode: none
interruptMode: immediate
followUpMode: all
startup:
  quiet: true
  checkUpdate: false
collapseChangelog: true
github:
  enabled: true
todo:
  eager: false
  reminders:
    max: 5
async:
  enabled: true
mcp:
  discoveryMode: true
secrets:
  enabled: true
statusLine:
  preset: default
  separator: powerline-thin
hideThinkingBlock: true
retry:
  fallbackRevertPolicy: cooldown-expiry
steeringMode: all
completion:
  notify: "on"
compaction:
  strategy: context-full
  thresholdPercent: -1
bash:
  autoBackground:
    enabled: true
dev:
  autoqa: false
