// codebase-memory-mcp:start
// Generated by codebase-memory-mcp for OpenCode.
// Regenerated on install/update from the MCP tool registry, so it cannot
// drift from the tools the server actually serves. Edits inside this block
// are overwritten; edit outside it, or remove the markers to take ownership.
// OpenCode already reaches every tool over MCP; this adds only the
// automatic graph lookup before a grep/glob, which other clients get
// through their own hook configuration.
import { spawn } from 'node:child_process';

const BIN = '/var/folders/_c/lqhw9pwj2g14cxrr4bdbfgn80000gn/T/opencode/cbmhome/.local/bin/codebase-memory-mcp';

function augment(tool, args) {
  return new Promise((resolve) => {
    const child = spawn(BIN, ['hook-augment'], {
      stdio: ['pipe', 'pipe', 'ignore'],
      env: { ...process.env, CBM_LOG_LEVEL: 'error' },
    });
    let out = '';
    child.stdout.on('data', (d) => (out += d.toString()));
    child.on('error', () => resolve(''));
    child.on('close', () => resolve(out));
    child.stdin.end(JSON.stringify({
      hook_event_name: 'PreToolUse',
      tool_name: tool,
      tool_input: args ?? {},
    }));
  });
}

export const CodebaseMemory = async () => ({
  'tool.execute.after': async (input, output) => {
    const tool = input?.tool === 'grep' ? 'Grep' : input?.tool === 'glob' ? 'Glob' : null;
    if (!tool) return;
    const extra = await augment(tool, output?.args);
    if (extra && typeof output?.output === 'string') {
      output.output += '\n' + extra;
    }
  },
});
// codebase-memory-mcp:end
