[session]
default_tool = "pi"

[sandbox]
enabled_by_default = true
default_image = "aoe-pi:latest"
environment = [
  "TERM",
  "COLORTERM",
  "FORCE_COLOR",
  "NO_COLOR",
  "EMAIL",
  "GIT_AUTHOR_NAME",
  "GIT_COMMITTER_NAME",
  "GITHUB_TOKEN",
  "ZAI_API_KEY",
  "MINIMAX_API_KEY"
]
